### ISSUE TITLE
Do not consider an empty DNP/dnp field as do not place - require '1'

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#101]
I had a few components that were missing from the BOM generated under KiBot.
It turned out that there was an empty dnp field:
![image](https://user-images.githubusercontent.com/1504752/141597429-d239a72e-aef1-4c2a-81dd-7a697d545390.png)

An empty dnp field should not be counted as a do not place value - it's only a dnp if the value is set to 1 (or not 0).

**Comment by set-soft** [comment]
Thanks @mdeweerd !

It was implemented before we added this clarification to the docs.

I don't have a test case at hand, I just changed the regular expression to avoid filtering empty fields. Let me know if it works for you.

**Comment by mdeweerd** [comment]
I'ld have to create a test case too, I adjusted the schematic files.  I'll probably create a few test cases ;-).
