### ISSUE TITLE
render_3d output naming & orthogonal output

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#110]
Edit: I introduced an error when creating my test case - orthogonal was written like ortogonal :-( .

I generate 3D normal and 3D orthogonal output (=2D equivalent).

This is the configuration file:
[test.zip](https://github.com/INTI-CMNB/KiBot/files/7564090/test.zip)

The filenames clash when using the common generic rule.
Could the naming of the output slightly change for the orthogonal projection so that the general rule can be changed without having to update the "output" naming rule specifically for these targets?

Mayby add "2D" rather than "3D".  Or just add "O" (https://www.abbreviationfinder.org/acronyms/omit_orthogonal.html )?

Otherwise, the implementation works well - its more than expected because you added the color changes, etc as well ;-) AND the orthogonal output.

(I have some kicost stuff in the configuration file to try to get a testcase for something else).

**Comment by mdeweerd** [comment]
I editedt the initial messange and I add that the 3d rendering alsow leaves me with some tmp*.pro files after the process .

**Comment by set-soft** [comment]
> Could the naming of the output slightly change for the orthogonal projection so that the general rule can be changed without having to update the "output" naming rule specifically for these targets?

I suggest using different target directories. I like to generate red, blue and green PCB views ... should I also add the color to the name? ;-)
But I think I have a solution.

> the 3d rendering alsow leaves me with some tmp*.pro files after the process .

Yes, KiCad creates project files if they don't exist. I committed a patch to remove them.

**Comment by set-soft** [comment]
Try the `id_add` option, it will be concatenated with the %i value. Now we can also have `_red` ;-)

**Comment by mdeweerd** [comment]
;-)  I hope that you'll experience the benefit from it ! - id_add is a better solution.  
Codewise, I often end up adding a common FilenameBuilder class or so.
