### ISSUE TITLE
Unable to generate `/root/workdir/%f_%r_%d%v/PCBWay/...

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#111]
I updated the "variant_4" testcase.   Tag failing_pcbway_compress: https://github.com/mdeweerd/KiBot/releases/tag/failing_pcbway_compress .

To reproduce this error:

> ERROR:Unable to generate `/root/workdir/%f_%r_%d%v/PCBWay/kibom-variant_4__2021-11-18_19-31-13-F_Cu.gtl` from 'Gerbers compatible with PCBWay' (PCBWay_gerbers) [gerber] (kibot.out_compress - out_compress.py:142)

execute this command in Docker VM:
```
kibot -e tests/board_samples/kicad_5/kibom-variant_4.sch -b tests/board_samples/kicad_5/kibom-variant_4.kicad_pcb -c tests/yaml_samples/step_variant_2.kibot.yaml -g variant=topvariant schematic_color bom steptopvariant stepleftvariant gerbers compress PCBWay_gerbers PCBWay_drill PCBWay
```

**Comment by set-soft** [comment]
Thanks.

Note that just attaching `kibom-variant_4.kicad_pcb`, `kibom-variant_4.sch`, `PCBWay2.kibot.yaml` and `step_variant_2.kibot.yaml` is better.
