### ISSUE TITLE
Download the datasheets

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#119]
This is a feature proposal to download the datasheets from the urls defined in the KiCAD component details.

I have a perl script that reads the CSV BOM as generated by KiCAD which gets all the datasheet urls, combines them and then creates a shell script allowing me to download these PDFs to the "DOC" folder.

The line generated for a download looks like this:
```bash
if [ ! -e DOC/430182070816.pdf ] ; then wget 'https://omronfs.omron.com/en_US/ecb/products/pdf/en-b3f.pdf' --no-check-certificate  --user-agent='Mozilla/5.0 (Windows NT 5.2; rv:2.0.1) Gecko/20100101 Firefox/4.0.1' -O DOC/430182070816.pdf ; fi
```

I then execute that script manually - I generated a script so that I could make small amendments if needed.  
The generated lines check if the file was downloaded already or not.  
That script does not do a log of error checking - I get empty output files when the URL is invalid.  
The original filename is (re)named to the 'manf#' regardless of the original name in the URL.  Some URLs would have the name in one of the GET parameters and not name them intelligently in the HTTP headers.

I guess this would be best added to one of the BOM tools (KiCost/KiBOM?) and eventually make it to KiBot.

My script being in perl, and not quite complex in itself, there's probably no use in sharing it.  Reading/building the BOMs rely on more advanded processes in the programs mentioned above.

**Comment by set-soft** [comment]
Ok, I implemented something. The code is passing a simple test called `test_download_datasheets_1`.

- Currently the code uses Python's internal stuff to download the PDFs. I don't know if it works for every site in the world, but doesn't need extra tools.
- The output name is customizable. 
- It supports variants.
- I know we could get the URLs from the metadata we get from distributors. But this won't be possible until I finish the KiCost integration (which needs to solve the KitSpace dependence).
