### ISSUE TITLE
Support filtering errors/warnings on output-specific basis, or for all outputs

### ISSUE THREAD

**Issue by justyn** [INTI-CMNB/KiBot#15]
Currently, the BoM tool throws some warnings for my configuration that are not useful.

It would be useful as a general capability to be able to filter errors/warnings elsewhere as seems to be possible for ERC/DRC.
Either applying a filter to all outputs, or (even better) to a specific output.

Thanks!

**Comment by set-soft** [comment]
This patch should solve the problem.

Let me know if something isn't covered by it.

**Comment by justyn** [comment]
Just tried this and it works, thanks
