### ISSUE TITLE
Marking components DNF flips their symbol on the Schematic

### ISSUE THREAD

**Issue by bugadani** [INTI-CMNB/KiBot#155]
I have the following in my schematic editor:
![image](https://user-images.githubusercontent.com/977627/155319734-4b41e89c-a9ec-4866-a936-887272a3c607.png)

J7 and J8 are both marked as DNF

KiBot generates the following in the schematic:
![image](https://user-images.githubusercontent.com/977627/155319830-e9b6ce2f-6af3-45b8-aed8-78661d8f28ff.png)

Note how J7 was mirrored on the KiBot output

I'm using KiCad 6 with the `INTI-CMNB/KiBot@v1_k6` github action if it makes any difference.

**Comment by set-soft** [comment]
Can you upload a simple example to a github repo? One with just these connectors.

**Comment by bugadani** [comment]
Repo with kibot generated artifact: https://github.com/bugadani/kibot_dnp_mirroring/actions/runs/1888114531

**Comment by set-soft** [comment]
Now should work. Lamentably this isn't [documented](https://dev-docs.kicad.org/en/file-formats/sexpr-schematic/#_symbol_instance_section) and I forgot to make it fail for unknown component attributes.
