### ISSUE TITLE
Would it be possible to export Gencad?

### ISSUE THREAD

**Issue by flaminggoat** [INTI-CMNB/KiBot#159]
Kicad has the option to export Gencad files. A PCB supplier I use requests this file output for assembly. It would be helpful if Kibot could automate this.

**Comment by set-soft** [comment]
This isn't currently available and is ticky.
There are no Python interface for this and the GUI can't define a hot-key for this option.
Sure this could be added to KiAuto, but will be delicated (prone to fail because of slight GUI changes)
I'll  leave it as a low priority enhancement

**Comment by set-soft** [comment]
Ok @flaminggoat , time to test it ;-)

**Comment by set-soft** [comment]
Hi @flaminggoat !
KiCad 7.99 is changing some text angle in GenCad files. Do you know about any tool to view these files to check if this is wrong?
