### ISSUE TITLE
Revision variable with KICAD 6 on bom export

### ISSUE THREAD

**Issue by stevaedrum** [INTI-CMNB/KiBot#163]
Hi,

I have detected an error with the set_variable option with export in master [[fc28b6a](https://github.com/INTI-CMNB/KiBot/commit/fc28b6a2574ae28c7d32fb7a44c07102367fc687)](url)
  - name: 'bom_html'
  - name: 'bom_xlsx'

Please see below, the value for the "Revision" not correct.

![image](https://user-images.githubusercontent.com/24732373/158478556-e6de6944-4c6f-4dea-b3af-96c3f48ca2d9.png)

Thank in advance for your help.

Best Regards

**Comment by set-soft** [comment]
Hi @stevaedrum !
The above patch should fix it. Please try if it works for you.

**Comment by stevaedrum** [comment]
Hi @set-soft ,

Great, it's correct, thanks you for your update.
