### ISSUE TITLE
check_zone_fills doesn't re-fill after text replacement

### ISSUE THREAD

**Issue by richardbarlow** [INTI-CMNB/KiBot#165]
If there is text on a copper layer that contains a variable that is replaced through the `pcb_replace` mechanism and `check_zone_fills` is set to true it looks like the fills are not actually refilled after the text replacement. This results in out-of-date fills with text overlapping the fill:

![Screenshot from 2022-03-22 17-45-45](https://user-images.githubusercontent.com/1657365/159543241-3497d977-cd49-4a7f-a1ec-24b27301014d.png)

Note that there is identical text on both the bottom copper and bottom silk layer in that screenshot and yes, I need to define a keep-out to prevent stitching vias being placed in that area.

I know that it's risky having the copper modified automatically, but I'm trusting that the DRC will catch any big issues and I always manually review gerbers before manufacture anyway

**Comment by set-soft** [comment]
Hi @richardbarlow !
Is this affecting outputs? or is just that you don't see the .kicad_pcb file updated?
Because `check_zone_fills` isn't `refill_zones` ... is just something we do before generating the outputs (and never saved)

**Comment by richardbarlow** [comment]
Ah, I only observed this when I opened the .kicad_pcb file after running KiBot. It never occurred to me to check the gerbers :facepalm:. I have just checked and the gerbers are correct, with refilled zones.

Since other modification operations performed by KiBot are saved to the .kicad_pcb file (string replacement) it would be helpful of the refilled zones were also saved. This would make debugging issues with the build much easier as it would be possible to view the exact source file that KiBot then used to generate fabrication data.

An alternative might be for KiBot to not modify the original source file at all and have the option of a new 'output' that allows you to save the fully modified .kicad_pcb file?

**Comment by set-soft** [comment]
I was thinking about the option to save the PCB, but this is interesting for other things, like variants.

I just added a different preflight option that just fills the zones and saves the PCB. So you can choose which one is better for your use ;-)
