### ISSUE TITLE
Excellon blind/buried drill files don't get included in archives

### ISSUE THREAD

**Issue by richardbarlow** [INTI-CMNB/KiBot#166]
Using KiCAD 6.0.2 and a layout that has blind and buried vias the drill files generated by the 'excellon' output don't get included in an archive when referencing it with 'from_output'. Also, the file names generated don't seem to be using the correct format. E.g:

```
-rw-rw-r--. 1 rbarlow rbarlow 8175 Mar 23 17:07 gpwdev-drill_gpwdev_v2.0.0-41-g465a4c4.drl
-rw-rw-r--. 1 rbarlow rbarlow 1883 Mar 23 17:07 gpwdev-drill_report_gpwdev_v2.0.0-41-g465a4c4.txt
-rw-rw-r--. 1 rbarlow rbarlow 3259 Mar 23 17:07 gpwdev-front-in1.drl
-rw-rw-r--. 1 rbarlow rbarlow 1510 Mar 23 17:07 gpwdev-in1-in2.drl
-rw-rw-r--. 1 rbarlow rbarlow  752 Mar 23 17:07 gpwdev-in2-back.drl
```

**Comment by set-soft** [comment]
Hi @richardbarlow !
You are right, the blind vias aren't supported.

**Comment by set-soft** [comment]
The above patch should work. 
It passes some trivial tests.
