### ISSUE TITLE
Screencasts generated when running with -v are included as an 'output'

### ISSUE THREAD

**Issue by richardbarlow** [INTI-CMNB/KiBot#168]
When running with '-v' the screencasts generated seem to get included the list of files generated by an output. This means that they end up included in zip files generated with the 'compress' output when using 'from_output'. Personally I would prefer that these debug files do not get included in the zip file (although I imagine that this doesn't apply to everyone). Would it be possible for the 'from_output' option of 'compress' to gain the ability to specify if debug files are included?

**Comment by set-soft** [comment]
Hi @richardbarlow !
This is strange because `from_output` uses `get_targets` and this member won't include debug videos.
Do you have a small example? Are you sure it isn't collected by a `source`?
It could be a problem with a particular output.

**Comment by richardbarlow** [comment]
Sorry, another face-palm moment. The screencast that I witnessed being included was generated when performing the ERC. Since the ERC report is not produced as part of a 'normal' output I have had to use `source` and had the pattern `*erc*`. Changing the pattern to `*erc*.txt` has fixed it.

Sorry for wasting your time.

**Comment by set-soft** [comment]
No problem, we all make mistakes
