### ISSUE TITLE
Text replacement not occuring in board renders

### ISSUE THREAD

**Issue by KenwoodFox** [INTI-CMNB/KiBot#173]
Looks like variable text replacement dosent happen in board renders?

![image](https://user-images.githubusercontent.com/31870999/161366218-61230733-89a4-4923-bfd1-9823846063b9.png)

It seems to work fine for the schematic view though
![image](https://user-images.githubusercontent.com/31870999/161366225-be5fddf1-c95d-47f3-9343-00afe997f790.png)
![image](https://user-images.githubusercontent.com/31870999/161366234-4783e71a-0b16-451f-a5f3-fafc8867bbcd.png)

**Comment by KenwoodFox** [comment]
I should note that this is kicad 6! And the readme does mention it being broken in this release!

**Comment by KenwoodFox** [comment]
Text replacement does work for the gerber files though 
![image](https://user-images.githubusercontent.com/31870999/161369289-dbdd638b-11ae-44a1-9fac-d1ff82bbfc78.png)

**Comment by set-soft** [comment]
Ok, I fixed this problem in `render_3d` output.

Note that this problem was because we need to copy the project along with any temporal PCB file. This wasn't needed before the introduction of text variables. So you could find the same problem on other outputs.

**Comment by KenwoodFox** [comment]
Confirmed! Fixed! 
![image](https://user-images.githubusercontent.com/31870999/161394483-a61005a5-4c76-46a2-a879-6cc96b7d8600.png)

This is an incredible amount of issues fixed in such a short time! I am very impressed and appreciative of your hard work!

**Comment by KenwoodFox** [comment]
Im wondering if its because i use `-s all` in the gitlab ci job and maybe its not running the preflight text replacement?

**Comment by KenwoodFox** [comment]
Im wondering if its because i use `-s all` in the gitlab ci job and maybe its not running the preflight text replacement?

**Comment by set-soft** [comment]
Most probably. Is this the only call to KiBot in the workflow?

**Comment by set-soft** [comment]
Try using `-s run_erc,run_drc` or similar

**Comment by KenwoodFox** [comment]
Its not the only one, ive got a drc and erc check formatted like this: 

```yaml
- "kibot -e hardware/ID-4001-WIFI/ID-4001-WIFI.kicad_sch -c hardware/config.kibot.yaml -d Fabrication -s update_xml,run_drc -i"
 ```

Can i force the `-s all` to explicitily do text replacement?

**Comment by set-soft** [comment]
> Can i force the `-s all` to explicitily do text replacement?

`-s run_erc,run_drc,update_xml`

**Comment by KenwoodFox** [comment]
That did it, thanks!
