### ISSUE TITLE
KiCAD 6 render_3d not rendering traces

### ISSUE THREAD

**Issue by KenwoodFox** [INTI-CMNB/KiBot#177]
Looks like kibot is not rendering traces with or without raytracing on

local
![image](https://user-images.githubusercontent.com/31870999/162023899-4e2253de-9a44-4b0d-8341-a9e70cfaa00f.png)

kibot ci/cd
![image](https://user-images.githubusercontent.com/31870999/162023918-6171d934-3ddb-4eb6-a96e-07126f3a82d7.png)

**Comment by set-soft** [comment]
Hi @KenwoodFox they are rendered, you just can't see them ;-)
Now seriously: is a transparency/opacity issue, KiCad 6 needs solder mask color to be sligthly transparent, so you can see the traces. I'm adding some code to force it for colors defined by name.
