### ISSUE TITLE
PCB without schematics

### ISSUE THREAD

**Issue by hoijui** [INTI-CMNB/KiBot#18]
In my [for-science-keyboard example](https://github.com/hoijui/for-science-keyboard/tree/oseg), there are 3 PCBs, but only one of them has a schematics file (the others are just "casing", basically). when I run kibot with a PCB file that has no schematics, kibot grabs the schematics file of the other PCB, from the same directory. it does so, even if I set the schematics file to "" with the command line argument. This can also be seen in the latest CI build output.

.. I am sorry I.. don't work cleanly these days. maybe this is also just a simple oversight by me.

**Comment by set-soft** [comment]
As I don't have more information, and I don't see what's the exact problem (other than a confusing message for a confusing situation) I'll close it.

Feel free to reopen it if you have more information.
