### ISSUE TITLE
pcbdraw shows a weird artifact

### ISSUE THREAD

**Issue by KyleHunter** [INTI-CMNB/KiBot#187]
When using the following:
`  - name: pcb_top

    comment: "Renders - top"

    type: pcbdraw

    dir: "Renders"

    options:

      format: png

      show_components: all`

I get this:

[
![image](https://user-images.githubusercontent.com/4069146/163501983-b3197109-e787-4429-a6e1-ea15cda751e8.png)
](url)

Changing the format to jpg, show_components: none does not help. The STEP export and pdf_pcb_print on this PCB work perfectly as well

**Comment by nerdyscout** [comment]
I had some weird things using pcbdraw when a circular PCB got not working, but a PCB of 4x 1/4 arcs did. As you do have rounded corners I assume it is something similar. therefor I assume it is not an issue of kibot, but pcbdraw.

**Comment by KyleHunter** [comment]
> 

Yes, you're right. I just tried with a rectangular PCB and it worked perfectly.

**Comment by set-soft** [comment]
Hi @KyleHunter and @nerdyscout !

It would be nice to have a small test case that produces it. I tried a very naive one: [test.zip](https://github.com/INTI-CMNB/KiBot/files/8506930/test.zip)

And I got correct drawings:

![pp-top](https://user-images.githubusercontent.com/22823627/163842236-09088c6b-8985-45f1-9d28-24aad8832a6d.png)
![pp-bottom](https://user-images.githubusercontent.com/22823627/163842260-ecaaee1f-55bd-4a30-989b-ecdd8125f0ff.png)

**Comment by KyleHunter** [comment]
@set-soft Got it. I'll see if I can't work one up to show it. Appreciate it!

**Comment by set-soft** [comment]
Hi @KyleHunter !
A silly question: Are you sure your outline is perfectly closed? I mean: that each segment perfectly joins the next. Note that a small difference will make PcbDraw fail to construct an SVG patch that contains the board. In your image looks like 4 joints aren't perfect and you get a rectangular hole inside the board.

**Comment by KyleHunter** [comment]
@set-soft Yeah, 100% sure. Really odd, I tried simplifying the design so I could share, but was struggling to reproduce it. It's still there on the actual design though. I'll see what I can manage to do.

**Comment by set-soft** [comment]
Without further information I'll assume this is a problem when the PCB contour isn't closed.
This error could be fixed in PcbDraw, but it should be catched by KiCad.
I don't know if @yaqwsx has some comment about it.

**Comment by set-soft** [comment]
Hi @yaqwsx !
What about some kind of *tolerance*, lets say 0.1 mm (configurable). If you don't find a matching segment end you look for one that is 0.1 mm (or less) closer.

**Comment by set-soft** [comment]
Hi @KyleHunter !
This problem is fixed in my fork of PcbDraw: https://github.com/INTI-CMNB/PcbDraw/releases/tag/v0.9.0-2
Is a rounding issue in KiCad SVG generation.
