### ISSUE TITLE
Document #103 (3D Model selection)

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#190]
I was looking in the documentation to find how I should specify my model variants, but there is only a limited description of it.

Maybe it sould be documented a bit more?

Change: https://github.com/INTI-CMNB/KiBot/commit/84d6217d189a25be3c13f0b9f3bb5ee7e8252d2d

Issue : #103

**Comment by set-soft** [comment]
I was waiting for some feedback, but you are right it should be documented.
