### ISSUE TITLE
KiBot fails on KiCad 6 when a symbol has a pin with an alternative assignment

### ISSUE THREAD

**Issue by KyleHunter** [INTI-CMNB/KiBot#193]
Pretty much the title.

A schematic with this symbol:

![image](https://user-images.githubusercontent.com/4069146/164477052-ce1adf00-e678-43d3-9157-a8d237ae8e4a.png)

Will fail like this:

`ERROR:Unknown pin attribute "[Symbol("alternate"), "/WR", Symbol("input"), Symbol("line")]" (kibot - kiplot.py:262)`

This is on the initial running on KiBot, not when generating any specific output.

**Comment by set-soft** [comment]
Thanks @KyleHunter !

Too much undocumented features ... we must find them with the use.

**Comment by KyleHunter** [comment]
@set-soft Awesome, thanks! Trust me, I'm going to have a lotttt more feedback coming up. Switching over my company to using KiBot to handle our output generations.
