### ISSUE TITLE
/usr/share/kicad/symbols/Device.kicad_sym`: Missing library signature

### ISSUE THREAD

**Issue by geoffreymbrown** [INTI-CMNB/KiBot#195]
I'm migrating a design from Kicad 5 to 6.  I've used kibot successfully in the past and installed the latest from github on a new machine with a fresh install of Kicad 6 (no 5 on this machine).   I get the following error when I run kibot

ERROR:At line 1 of `/usr/share/kicad/symbols/Device.kicad_sym`: Missing library signature (kibot - kiplot.py:264)
ERROR:Line content: `(kicad_symbol_lib (version 20211014) (generator kicad_symbol_editor)` (kibot - kiplot.py:265)

This seems to be an issue with the interaction of kibot and the default kicad library

**Comment by geoffreymbrown** [comment]
This seems to be a migration issue -- the pre-migration kicad files caused issues

**Comment by set-soft** [comment]
Yes, mixing v5 and v6 files confuses KiBot, if v6 is installed and you load a .sch KiBot will try to load v5 libs, but will find v6 libs.
You should get a warning about this situation (using v5 files on v6 installation)
