### ISSUE TITLE
xml.parsers.expat.ExpatError: not well-formed (invalid token)

### ISSUE THREAD

**Issue by erichstuder** [INTI-CMNB/KiBot#206]
Hello

I try to create fabrication outputs.
So I set up a first simple GitHub Action that uses INTI-CMNB/KiBot@v2_k6 with quickstart: YES.
There is no .kibot.yaml file

Repository and branch:
https://github.com/erichstuder/RemoteControl/tree/pcb_fabrication_outputs

yml file:
https://github.com/erichstuder/RemoteControl/blob/pcb_fabrication_outputs/.github/workflows/pcb_fabrication_outputs.yml

The output:
https://github.com/erichstuder/RemoteControl/runs/6810837356?check_suite_focus=true
[logs_3.zip](https://github.com/INTI-CMNB/KiBot/files/8869667/logs_3.zip)
see in the zip file: `generate_fabrication_outputs/4_Run INTI-CMNBKiBot@v2_k6.txt`

At the end it says: _xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 587_

As these are my first steps with KiBot and GitHub Actions I'm unsure whether I did something wrong.

The problem seems to be a file that is "not well-fomed". But which one?
What could possibly be wrong?

Thank you very much

**Comment by set-soft** [comment]
Hi @erichstuder !
The problem was with field names containing `/`. Now should work, but you'll need to use the `v2_dk6` tag instead of `v2_k6`. At least until a new release is done.
Thanks for reporting

**Comment by erichstuder** [comment]
It's working now!
Thank you.
