### ISSUE TITLE
[BUG] Gerbers missing some F.silks, but present in KiBot render and KiCad Gerbers

### ISSUE THREAD

**Issue by mmccoyd** [INTI-CMNB/KiBot#235]
**Describe the bug**
Gerbers missing some F.silks, but present in KiBot render and KiCad Gerbers. Most front silks are present.

**To Reproduce**
Run the Fab and Doc GitHub Actions of https://github.com/mmccoyd/hillside/tree/_46. Look at the Gerbers produced by the fab action and the render produced by the doc action. 
Current commit is: 162e8e4   "46: PCB: Update pad footprint, attempting silk fix"

**Expected behavior**
Expected silks showing in KiCad gerbers, 3D view, and KiBot render to show in KiBot Gerbers. 

**Screenshots**

**Environment (please complete the following information):**
Running KiBot:
In GitHub action.
With uses: INTI-CMNB/KiBot@v2_k6

**Additional context**
There appears nothing unique about those silk elements

![KiBot Gerbers missing some F Silks](https://user-images.githubusercontent.com/4062658/180365757-09e66909-b118-47a1-8799-81ac6711787a.png)
![KiBot_render](https://user-images.githubusercontent.com/4062658/180365760-925e12ac-0891-4ce2-95df-2c9e9d18c0e0.png)
![KiCad Gerbers show all F Silks](https://user-images.githubusercontent.com/4062658/180365761-3fcb70f9-57bc-4367-8ae6-43cc646c102d.png)

**Comment by set-soft** [comment]
Hi @mmccoyd !
Nice PCBs!
The problem is that you are explicitly removing the footprint values: https://github.com/mmccoyd/hillside/blob/162e8e468674dcdf7fe66ac0c609566f5c6e3304/hillside46/bin/fab.kibot.yaml#L41

```
      plot_footprint_values: false
```

`Left_Board` is the value for JP2

**Comment by mmccoyd** [comment]
Ahh. Very sorry!  And very glad there is no weird bug. Great tool!
