### ISSUE TITLE
[BUG] "unconnected pads" error when running as a github action

### ISSUE THREAD

**Issue by computergeek1507** [INTI-CMNB/KiBot#245]
When I do DRC checking with kibot in a git action I get an error saying there are unconnected pads. I run DRC with the same project on my windows machine and get no unconnected nets.

**Expected behavior**
No "unconnected pads" error.

**Environment (please complete the following information):**
Where are you running KiBot:
- GitHub Action
- docker: container: setsoft/kicad_auto:dev_k6

- Using a desktop system? Which OS, distro and version?
 It works on Windows 10 and Fedora 36 with Kicad 6.0.7

Github Action
![image](https://user-images.githubusercontent.com/2293065/183980004-30d54359-0b16-4177-a045-fd7c5d188352.png)

Windows 10 DRC
![image](https://user-images.githubusercontent.com/2293065/183979855-adb2079d-270e-470f-baa1-fae699ed0571.png)

Link to github action if it helps
https://github.com/computergeek1507/PB_16/actions/workflows/drc.yaml

**Comment by set-soft** [comment]
Hi @computergeek1507 !
Thanks for reporting,  warnings and unconnected items are counted together. I fixed the message.
Now you should get:

```
- Running the DRC
ERROR:Found 0 DRC errors and 17 unconnected pad/s or warnings (pcbnew_do - pcbnew_do:1191) (kibot - kiplot.py:123)
```

If you choose to ignore the unconnected items this won't be fatal, just an error message (`ignore_unconnected: true`).

If you want to ignore those warnings just use:

```yaml
preflight:
  run_erc: false
  update_xml: false
  run_drc: true
  check_zone_fills: true
  ignore_unconnected: false
  filters:
    - error: silk_overlap
    - error: silk_over_copper
```
