### ISSUE TITLE
[FEATURE] Optimize "Executing" message in debug log for easy manual replay.

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#269]
Currently the debug log shows executions like this:

```
DEBUG:Executing: ['/usr/bin/git', 'rev-parse', '--abbrev-ref', 'HEAD'] (kibot - out_diff.py:46)
```

I suggest that that would show like this:
```
DEBUG:Executing: '/usr/bin/git' 'rev-parse' '--abbrev-ref' 'HEAD'
```

It would then be easier to replay by copy/paste to the console.

**Comment by set-soft** [comment]
I changed various logs to shlex.join(cmd), this should quote only the needed args.
BTW: I was using a similar mechanism for the regression tests, where I like to run the kibot command that failed just copying it.
