### ISSUE TITLE
[BUG] `update_qr` will always put QRs on the front of the board

### ISSUE THREAD

**Issue by Gigahawk** [INTI-CMNB/KiBot#271]
Fill as much as you can, remove the rest

**Describe the bug**

If a QR code is placed on the bottom of the board, when KiBot updates the QR code, it ends up on the front silkscreen instead.

**To Reproduce**

Link to CI run: https://github.com/Gigahawk/clickwheel_breakout_4th_gen/actions/runs/2969490566

In the regular source document, the QR code is placed on the bottom silkscreen:
![image](https://user-images.githubusercontent.com/10356230/187854541-fc801782-0aeb-4cc0-b95d-7ecc0e594d98.png)

However, in the output, the QR code itself ends up on the top silkscreen, while the text stays on the bottom:
![image](https://user-images.githubusercontent.com/10356230/187854721-08dfa3a6-af53-40f3-9185-d8074de2c14d.png)

**Expected behavior**
QR code should stay on the same side it is originally placed on

**Screenshots**

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow? GitHub Actions
- In a GitHub action? Which tag are you using? (Ex `v1`, `v1_k6`, `v2`, `v2_d`, `v2_dk6`, `v2_k6`)
- Using a docker image? ki6.0.7_Debian
- Using a desktop system? Which OS, distro and version? Windows + WSL

**Additional context**

**Comment by set-soft** [comment]
Hi @Gigahawk !
This patch should fix the issue.
Thanks for reporting
