### ISSUE TITLE
[FEATURE] KiDiff - difference between variants

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#278]
I do not think the current implementation allows to create the diffrence of variants.

Diffing variants helps verify that the differences are those that are expected.

This could be an option that is a list of all the variants to compare and they would be compared for every possible combination.  Three variants (A,B,C) -> 3 differences (AB,AC,BC).

**Comment by set-soft** [comment]
Hi @mdeweerd !
Now is possible, you can also compare a reference file with all the listed variants (IMHO easier to understand).

P.S. I know, the names are ugly, but they are different and contains the needed info.
