### ISSUE TITLE
[BUG][pcb_print] Custom text variables on drawing layers are not being replaced

### ISSUE THREAD

**Issue by cdwilson** [INTI-CMNB/KiBot#280]
**Describe the bug**
Custom text variables on drawing layers (User.Drawings, F.Fab, etc.) are not being replaced.  However, custom variables in the worksheet title block, and built-in text variables are correctly replaced:

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/14631/188325500-0dbe67c6-eb20-4dd4-b76e-29191e5c8ef1.png">

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/14631/188325463-820eb99e-80d7-4356-810d-32280e8572bf.png">

Built in text variables are correctly replaced:

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/14631/188324741-b6752d2c-0476-4bcd-9cce-548f4f87c920.png">

All text variables are correctly replaced in the KiCad GUI:

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/14631/188324814-defe6182-31e2-462e-ba91-46f0ade9bd63.png">

**To Reproduce**

```
git clone --branch text-vars-not-working git@github.com:cdwilson/test-kibot.git
cd test-kibot
make
# open _build/PDF/fab_drawing.pdf
```

**Expected behavior**
Custom text variables should be replaced.

**Environment (please complete the following information):**
Where are you running KiBot:
- Using a docker image? `kicad_auto:dev_k6`

**Comment by set-soft** [comment]
Thanks for the example @cdwilson !
The problem was related to an aggressive caching done in KiCad, when reloading a PCB it tries to recycle the old project, even if we ask KiCad to load the project again, I had to unload it and then explicitly load it again.
