### ISSUE TITLE
[FEATURE] Add board layer control in the `3d_render` output

### ISSUE THREAD

**Issue by cdwilson** [INTI-CMNB/KiBot#282]
**Is your feature request related to a problem? Please describe.**
I was trying to generate a 3D render of the bare PCB with KiBot, and I don't think there is any way to turn off all the 3D models, paste, and adhesive layers.  Here's the best I was able to achieve:

```
      no_smd: true
      no_tht: true
```

![image](https://user-images.githubusercontent.com/14631/188524174-e023154f-e7e6-43ad-8436-79cf0935852d.png)

Here's an example of what I'd like to achieve:

<img width="673" alt="image" src="https://user-images.githubusercontent.com/14631/188523856-dda80319-769a-49e0-966f-2910fa94e402.png">

While trying to get this working, I realized that there are additional board layers options available in the 3D viewer which don't seem to be supported by KiBot's `3d_render` output.  It would be nice to support these additional options.

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/14631/188524101-c6cdec34-afd5-4d7a-88f0-7b817bf5d9a1.png">

**Comment by set-soft** [comment]
Now it should be possible.
Try using `show_solderpaste: false`
Needs KiAuto 2.0.4

**Comment by cdwilson** [comment]
Works great, thanks!

![image](https://user-images.githubusercontent.com/14631/189782818-a2e4fd76-e489-4bb3-b309-7e6d4d214ca9.png)
