### ISSUE TITLE
[BUG] Dimensions are not included in `dxf` output

### ISSUE THREAD

**Issue by cdwilson** [INTI-CMNB/KiBot#284]
**Describe the bug**
When exporting a DXF, the dimension elements are not included in the DXF output.  However, when exporting the same layer as a PDF, the dimension elements are printed correctly.

<img width="2524" alt="image" src="https://user-images.githubusercontent.com/14631/188567962-9fb32c91-e83d-4da2-af5a-6c2bf4d5a7ae.png">

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/14631/188567996-5ffad29e-ce85-4082-82b9-c2e7722b826e.png">

**To Reproduce**
```
git clone --branch dxf-dimensions-not-working git@github.com:cdwilson/test-kibot.git
cd test-kibot
make
# compare DXF vs. PDF outputs in _build/
```

**Expected behavior**
I expect the dimension lines to be included in the DXF output.

**Environment (please complete the following information):**
Where are you running KiBot:
- Using a docker image? `kicad_auto:dev_k6`

**Comment by set-soft** [comment]
What do you get using KiCad GUI?

**Comment by set-soft** [comment]
I can't even open the DXF files created by KiCad

**Comment by cdwilson** [comment]
Hi @set-soft sorry, you are correct.  I thought this was working in KiCad GUI, but it turns out that it only works if "Plot graphic items using their contours" is unchecked...  When I check this box, it fails in the KiCad GUI also.

<img width="825" alt="image" src="https://user-images.githubusercontent.com/14631/188688984-862ab8be-053d-4e92-81e8-7b65e98e222f.png">

FYI, there is already an issue reported for this: https://gitlab.com/kicad/code/kicad/-/issues/11901

**Comment by set-soft** [comment]
Ok, then just use the `polygon_mode: false` option
