### ISSUE TITLE
[HOW] Issues with malformed component reference

### ISSUE THREAD

**Issue by 1zun4** [INTI-CMNB/KiBot#322]
**What do you want to achieve?**
I want to generate the required files for JLPCB. Means gerber, excellon, position and BOM.

It will always fail and complain about Malformed component reference "12V1".
![grafik](https://user-images.githubusercontent.com/69533520/198821291-7c7a5b14-63b0-456f-94be-b25555cd12f5.png)

which is specified in the following files:
https://github.com/m365fw/MP2_ESC/blob/a07c098d74e35349fdd8309aae0e1ac12c350291/versions/v0.1/CCC_ESC.kicad_sch#L9562
https://github.com/m365fw/MP2_ESC/blob/a07c098d74e35349fdd8309aae0e1ac12c350291/versions/v0.1/CCC_ESC.kicad_sch#L11629

**Do you have some PCB/Schematic to use as example?**
https://github.com/m365fw/MP2_ESC/tree/kibot_workflow/versions/v0.1

**Do you have some configuration file (.kibot.yaml) that you are using?**
https://github.com/m365fw/MP2_ESC/blob/a07c098d74e35349fdd8309aae0e1ac12c350291/config.kibot.yaml

It is the example config for the JLPCB configuration.

**Environment (please complete the following information):**
GitHub CI

**Additional context**

**Comment by set-soft** [comment]
Hi @1zun4 !
Just use the same pattern you use for the rest of the references in your design: PREFIX/NUMBER
Like KiCad tries to show (R?, C?, etc.)
For a short fix you can even use the same pattern you used for other test points: TpWHATn
In this case, using Tp12V1 solves the problem.
But I *strongly* recommend using TpN and let the "12V" only for the Value. You don't use "R4K7" for the reference of a "4K7" resistor ;-)
