### ISSUE TITLE
PDF output from pcb_print not searchable

### ISSUE THREAD

**Issue by axemag** [INTI-CMNB/KiBot#331]
We have been using Kicad automation for many years maintaining a bunch of our own scripts together with forks of KiPlot, KiAuto etc. Thanks to the hugely impressive work you are doing, we no longer have the need to fork anything, your image found at Dockerhub is all we use.

However we do have an issue that is also mentioned by @richardbarlow in the more general discussion in #109. The output from pcb_print is not searchable, making it less ideal for assembly drawings that are sent to an EMS. If I follow your commit history correctly, in commit 4e659c3 the intermediate files produced by pcb_print were changed from PDF to SVG for performance reasons, however the SVG:s outputted from KiCad does not seem to preserve text and then of course the merged output also lacks searchable text.

Previously, when KiBot did not have as much features, I used pcb_pdf_print and added a quick hack to enable it to run a custom commands (#109) which called a bash-script to recolor and merge the pcb_pdf_print output. (For our use case, it's actually the horrible colors that are the show stopper, or we could have used pcb_pdf_print.) Now, when KiBot offers us everything needed except for searchable assembly drawings, I would much rather have it included in mainline KiBot.

@set-soft, what is your view on this? How should one go about this to achieve what I'm asking for? Is it of interest to the KiBot project? Can I help? I see several solutions, such as rewriting (reverting) pcb_print to use PDF:s, add a custom layer color option to pcb_pdf_print (but I guess pcb_print is preferred), add custom post-processing commands (but it would be better if all functions were in KiBot), writing a completely new output etc. But I'm not sure which would be the preferred solution for the project.

Thanks!

**Comment by set-soft** [comment]
Hi @axemag !
It took me some time to figure out why the text wasn't searchable. I finally figured out that `rsvg-convert` drops transparent text. So I'm now changing the opacity from 0 to 0.01. As far as I can see it remains invisible, but isn't removed.
I was able to search for text on a `pcb_print` output. Here is an example:

[light_control-assembly.pdf](https://github.com/INTI-CMNB/KiBot/files/10079246/light_control-assembly.pdf)

The highlight isn't always perfect, but seems to be usable.
