### ISSUE TITLE
V7 support?

### ISSUE THREAD

**Issue by ct2irw** [INTI-CMNB/KiBot#338]
Hi,

Any luck getting kibot to work with 6.99?

I'm having an issue with PCB_PLOT_PARAMS having no NO_DRILL_SHAPE... Guess SMALL_DRILL_SHAPE and FULL_DRILL_SHAPE are also gone...

Thanks,
Diogo

**Comment by set-soft** [comment]
Hi @ct2irw !
Supporting nightly KiCad snapshots is a big burden. 
I'll do it only when the v7 release is defined and the API becomes stable.
I can add patches, but only if somebody tells me what to change. I won't do it by myself.
I added 5.99 support in the past, and was really annoying, things changed over and over.
