### ISSUE TITLE
[BUG] Segfault when trying to process from within docker

### ISSUE THREAD

**Issue by jnavila** [INTI-CMNB/KiBot#347]
Fill as much as you can, remove the rest

**Describe the bug**

When launching kibot from within a container, the command results in segfault error.

**To Reproduce**

```sh
$ cd $project
$ docker run -it --rm -v $(pwd):/home/ -u $(id -u ${USER}):$(id -g ${USER}) ghcr.io/inti-cmnb/kicad5_auto:1.2.0     /bin/bash
I have no name!@8a47485d076e:/$ kibot
Segmentation fault (core dumped)
```
Note : kibot runs smoothly on the same project from within an installation on ubuntu 20/04 (where docker is installed)

**Expected behavior**

The file is processed.

**Comment by set-soft** [comment]
Hi @jnavila !
You are running KiBot in a very broken environment. You are forcing a user ID that doesn't exist in the docker space, this is why you get `I have no name!` as user name.
You should map your /etc files like this:

```
#!/bin/sh
export USER_ID=$(id -u)
export GROUP_ID=$(id -g)
docker run --rm -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY \
    --user $USER_ID:$GROUP_ID \
    --env NO_AT_BRIDGE=1 \
    --workdir="/home/$USER" \
    --volume="/etc/group:/etc/group:ro" \
    --volume="/home/$USER:/home/$USER:rw" \
    --volume="/etc/passwd:/etc/passwd:ro" \
    --volume="/etc/shadow:/etc/shadow:ro" \
    --volume="/home/$USER:/home/$USER:rw" \
    setsoft/kicad_auto_test:latest /bin/bash
```

I don't have much time now, but the crash is most probably in KiCad's module.
