### ISSUE TITLE
[BUG] PCB dimensions in report file are not correct

### ISSUE THREAD

**Issue by alexanderwiller** [INTI-CMNB/KiBot#375]
**Describe the bug**
The report generated by the output `type: report`  reports inaccurate dimensions. A PCB manufacturer pointed this out to me.

Using the following KiBot config
```
kibot:
  version: 1

global:
  units: millimeters

outputs:
- name: report_full
  comment: Full design report
  type: report
  options:
    template: full_SVG
```
this line is generated in the report:
```
Board size: 28.75x52.5 mm (1.13x2.07 inches)
```

The area that encloses the full PCB outline on Edge.Cuts is larger than this, and is reported correctly by the following code:
```
>>> import pcbnew
>>> board = pcbnew.GetBoard()
>>> board.ComputeBoundingBox(True).GetWidth()
30050000
>>> board.ComputeBoundingBox(True).GetHeight()
57385000
>>> 
```

I got the idea to use `board.ComputeBoundingBox(True)` from the following code:
https://github.com/INTI-CMNB/KiBot/blob/5abffa8a552f0381ad9a6e7942e06781c28de332/kibot/out_report.py#L523

My guess therefor is that the "special handling" (which I did not invest time to fully comprehend) in https://github.com/INTI-CMNB/KiBot/blob/5abffa8a552f0381ad9a6e7942e06781c28de332/kibot/out_report.py#L526 is responsible for the deviation in dimensions.

**To Reproduce**
Use the attached board file and KiBot config with KiBot without extra CLI parameters.

[GitHub KiBot PCB dimensions bug.zip](https://github.com/INTI-CMNB/KiBot/files/10499005/GitHub.KiBot.PCB.dimensions.bug.zip)

**Expected behavior**
Correct `Edge.Cuts` bounding box dimensions are reported.

**Environment (please complete the following information):**
Where are you running KiBot: `ghcr.io/inti-cmnb/kicad6_auto:dev`

**Comment by set-soft** [comment]
Hi @alexanderwiller !
Thanks for the example!
Now should work. 
Note that the real size is 30x57.34 mm, not 30.05x57.385 mm
KiCad computes the width of the edge trace as part of the bounding box. The difference here is negligble, but when you created a 30x20 rectangle and get 30.1x20.1is quite annoying.
