### ISSUE TITLE
[HOW] setting text var based  on output job or CI pipeline 

### ISSUE THREAD

**Issue by MarkusSBS** [INTI-CMNB/KiBot#376]
Is it possible to set Text variables based on output Jobs or based on CI pipeline that is running? 

for exampe a text var ${doc status} replaced bei preliminary, draft, release, Hotfix etc.

```

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow? GitLab
- In a GitHub action? Which tag are you using? v2_k6
- Using a docker image?  `kicad_auto:dev_k6`,

**Comment by set-soft** [comment]
Hi @MarkusSBS !
You can set environment variables in your jobs.
Then you can set text variables using the environment variables.
I.e.

```yaml
preflight:
  set_text_variables:
    - variable: "DOC_STATUS"
      command: "echo $DOC_STATUS"
```

This will create a text variable with the content of the same environment variable.
And you can set the environment variable using a [job output](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)

Is this what you want?
