### ISSUE TITLE
[FEATURE] Generate PCB/PCBA Specification

### ISSUE THREAD

**Issue by andersruneson** [INTI-CMNB/KiBot#384]
**Is your feature request related to a problem? Please describe.**
When ordering boards from a larger EMS they normally request specifications for PCB and PCBA to help them with information such as stackup, material, solder mask color etc etc

**Describe the solution you'd like**
I have not found any way to generate this with KiBot, but maybe I missed some outputs.

**Describe alternatives you've considered**
Currently we use word files from a template that we manually fill in and add to the production files generated by kibot. We've also built our own tool for generating this but we have not yet integrated this tool into the CI toolchain and it would be so much better to have the options in the kibot.yaml instead of a separate config file for our own tool.

**Additional context**
Attached a couple of files that we generated from the word template.
[PCBA Specification.pdf](https://github.com/INTI-CMNB/KiBot/files/10560018/PCBA.Specification.pdf)
[PCB Specification.pdf](https://github.com/INTI-CMNB/KiBot/files/10560019/PCB.Specification.pdf)

**Comment by set-soft** [comment]
Related to this: KiCad 7 now supports:
- Place | Add Board Characteristics
- Place | Add Stackup Table

**Comment by set-soft** [comment]
The above patch adds a preflight to keep "Place | Add Board Characteristics" updated

**Comment by set-soft** [comment]
And now also the stackup table can be updated.
