### ISSUE TITLE
[FEATURE] more github actions tags

### ISSUE THREAD

**Issue by flaviut** [INTI-CMNB/KiBot#386]
**Is your feature request related to a problem? Please describe.**

I'm using the `INTI-CMNB/KiBot@v2_k6` github action, and all the sudden my actions seem to be failing. This seems to be related to a recent update of the `v2_k6` action, and the new version of KiCad crashes (segfaults) on my project.

**Describe the solution you'd like**

It makes sense to have an evergreen tag like `v2_k6`, but it would also be nice to have a pinned version, like `v2.0.0_k6` that never changes and allows a working github actions workflow to work forever, regardless of any changes that may occur.

**Describe alternatives you've considered**

None

**Comment by set-soft** [comment]
Hi @flaviut !
You already have `v2_k6_1_2_0` and `v2_k6_1_3_0` as explained in the [docs](https://github.com/INTI-CMNB/KiBot#github-actions-tags).

I'm changing the title to *more github actions tags* because 1.4.0 and 1.5.1 doesn't have tags

**Comment by set-soft** [comment]
Done, added tags for 1.4.0 and 1.5.1

**Comment by flaviut** [comment]
My mistake, I didn't see that part of the docs. Thank you!
