### ISSUE TITLE
[Question] kicost Unknown option `exclude_filter`

### ISSUE THREAD

**Issue by N0cynym** [INTI-CMNB/KiBot#389]
**Describe the bug**

```
WARNING:(W015) Unknown option `exclude_filter` (kibot - optionable.py:149)
```

Based on the knowledge of [this informations](https://github.com/INTI-CMNB/KiBot/issues/385#issuecomment-1419388298) I exclude the `_mechanical` filter for my PaP export to include fiducial markers.

To exclude them from BoM I turn back on the [exclude filter _mechanical](https://github.com/INTI-CMNB/KiBot/blob/cc2272e7028e43a2f880d06fc7c6467bfd7869fb/README.md?plain=1#L1052):

```yaml
 options:
      exclude_filter: _mechanical
```

This methode works perfectly for the types `bom`, `ibom` and `kibom` **but** not for `kicost`

**To Reproduce**

```
"kibot -g variant=default
             -d BoM/default/ 
             -s all bom_csv
                    bom_html
                    bom_xlsx
                    interactive_bom
                    costs_calc"
```

[Test-Bug.zip](https://github.com/INTI-CMNB/KiBot/files/10677759/Test-Bug.zip)

**Expected behavior**
Cost Calc should contain the same components as the other BoM's

**Environment (please complete the following information):**
Where are you running KiBot:
- In a `GitLab` CI/CD workflow
- Using a docker image`kicad_auto:dev_k6`

**Comment by set-soft** [comment]
Hi @N0cynym !
KiCost output doesn't currently have such an option, as I told you BoM does.
Use BoM output to get KiCost information.
