### ISSUE TITLE
Missing libraries on Ubuntu

### ISSUE THREAD

**Issue by eeintech** [INTI-CMNB/KiBot#41]
I was missing `xvfb` and `xdotool` on my Ubuntu 18.04 system, which I've installed using:
``` bash
$ sudo apt update
$ sudo apt install xvfb xdotool
```

Not sure if it was specific to my system or if that's a common theme for new KiBot users.
Would be nice if this was documented in the `Installation using pip` section!

**Comment by set-soft** [comment]
Thanks!
I added a note, you should be using the .deb file on Ubuntu.
I know a repo should be the ideal, but isn't that hard downloading the .deb files and you get **all** the dependencies solved.
