### ISSUE TITLE
[FEATURE] Add "use_aux_axis_as_origin" for VRML output

### ISSUE THREAD

**Issue by rainer38** [INTI-CMNB/KiBot#420]
**Is your feature request related to a problem? Please describe.**
When i export the VRML file i manually have to set the ref_x and ref_y coordinates to my aux origin from the pcb to set the correct origin in the exported file.

**Describe the solution you'd like**
Add an option "use_aux_axis_as_origin" like with other output types to set the ref_x and ref_y automatically to the aux origin of the pcb.

**Describe alternatives you've considered**
I've written al little python script which parses the KiCAD pcb file to get the aux origin and modify the kibot.yaml with the result. But this would mean i have to generate a specific kibot.yaml for every project instead of using one global config file.

**Comment by set-soft** [comment]
Hi @rainer38 !
Try the above patch

**Comment by rainer38** [comment]
This also works very good.
