### ISSUE TITLE
[FEATURE] Please add a variable for the main folder name of the KiCAD project

### ISSUE THREAD

**Issue by rainer38** [INTI-CMNB/KiBot#421]
**Is your feature request related to a problem? Please describe.**
I need a variable which contains the main KiCAD project folder name without the whole path.
For example if the project path would be "/home/user/Documents/kicad_project/testfile.kicad_pcb" the variable would contain "kicad_project".
My projects does not always have the same file- and folder name but the folder name is the one i need for generating output files.

**Describe the solution you'd like**
Please add a variable like %M (or something else) which represents the folder name of the KiCAD project.

**Describe alternatives you've considered**
I wrote a little python script which extracts the folder name and substitutes placeholders within the kibot.yaml file. But than i have to create custom configuration files for every project instead of using a global configuration.

**Comment by set-soft** [comment]
Hi @rainer38 !
The above patch should do it, please test it. It passed a naive test.

**Comment by rainer38** [comment]
It works like a charm. Thanks for the fast reaction. :)
