### ISSUE TITLE
[HOW] 3D rendering illumination too high?

### ISSUE THREAD

**Issue by rainer38** [INTI-CMNB/KiBot#423]
**What do you want to achieve?**
I want to get 3d renderings the same way they are generated from kicad pcb 3d viewer.
But the generated 3d renderings seems to have much higher illumination which make the images look like they are overexposed.
Are there any configuration parameter which i have to tune to get better results?

**Do you have some PCB/Schematic to use as example?**
All generated images have this over exposition, especially in the top and bottom view when the view shows on the surface in 90 degrees.

Here is an image from kicads 3d viewer:
![testprojekt](https://user-images.githubusercontent.com/21087560/232282681-350c552e-7629-486f-a472-31ab4af18d63.png)

And here the same view from kibot:
![testprojekt_v1 2_3D_top](https://user-images.githubusercontent.com/21087560/232282751-b0f0a6c4-3455-4a82-a115-9574b9d2e517.png)

**Do you have some configuration file (.kibot.yaml) that you are using?**
```yaml
- name: render_3d_top
  comment: 3D Ansicht von oben
  type: render_3d
  options:
    download: false
    orthographic: false
    auto_crop: false
    ray_tracing: false
    view: top
```

**Environment (please complete the following information):**
KiBot 1.6.2 - Copyright 2018-2023, Salvador E. Tropea/INTI/John Beard - License: AGPL v3

Application: KiCad
Version: (7.99.0-731-g32eb1ef77e-dirty), release build
Libraries:
	wxWidgets 3.0.5
	FreeType 2.10.4
	HarfBuzz 2.7.4
	FontConfig 2.13.1
	libcurl/7.88.1 GnuTLS/3.7.1 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
Platform: Debian GNU/Linux 11 (bullseye), 64 bit, Little endian, wxGTK, KDE, x11
Build Info:
	Date: Apr 10 2023 18:30:30
	wxWidgets: 3.0.5 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.24
	Boost: 1.74.0
	OCC: 7.5.1
	Curl: 7.88.1
	ngspice: 39
	Compiler: GCC 10.2.1 with C++ ABI 1014
Build settings:
	KICAD_SPICE=ON

**Comment by set-soft** [comment]
Hi @rainer38 !

Just play with the PCB color. It is currently too light. This is a problem with the way colors are interpreted by different tools. I tried to unify them, but looks like some are using RGB and others sRGB. I didn't have time to investigate which gamma correction fixes it.

That said, I'll recommend you to avoid using *render_3d*, use *blender_export* instead. I know it will need more RAM and more CPU time, but the results are worth the spend resources. The KiCad developers told me they won't add a *kicad-cli* command for 3D View in the near future. So this output relies on handling the GUI, which is prone to errors. On the other hand Blender has a usable Python API and is in the "full" docker images.
