### ISSUE TITLE
[HOW] KiCad 7.0.2

### ISSUE THREAD

**Issue by set-soft** [INTI-CMNB/KiBot#425]
Lamentably KiCad 7.0.2 was released too early, with some very annoying bugs:

1. All power symbols will produce an ERC error about a missing simulation model. This ERC rule will default to IGNORE in 7.0.3 (see KiCad commit [37a42a3fb7](https://gitlab.com/kicad/code/kicad/-/commit/37a42a3fb710de393651aa8b18379e46b55e577d)) and KiCad won't check simulation models for power sources or for components marked as excluded from simulation (see KiCad commit [f67a477f65](https://gitlab.com/kicad/code/kicad/-/commit/f67a477f65169454778fdd876f939666abefd56e)). For people using 7.0.2 just change the severity for *SPICE model issue* to *Ignore* (File menu, Schematic Septup option, Electrical Rules section, Violation Severity options)
2. ERC dialog some times closes right after finishing the ERC. In my tests this is when you get at least one error and the dialog shows the faulty marker in the main window. This is a bug in the code that does a refresh for the schematic window. It marks the update as if a SPICE model changed invalidating the ERC. So the ERC is performed, you get an error, the error is automatically selected, the schematic window is updated and ... the ERC is invalidated. This is KiCad bug [14538](https://gitlab.com/kicad/code/kicad/-/issues/14538), and I found the error using the debugger. This is already solved in the repo.
3. The EDA_ITEM.Duplicate() member doesn't cast the returning value. So some code using ZONES fails. This is the case for KiKit panelize. This was introduced by KiCad commit [8e579ec8e0](https://gitlab.com/kicad/code/kicad/-/commit/8e579ec8e0e8d485645d18cb5d897fc2174307c5) to fix KiCad bug [14660](https://gitlab.com/kicad/code/kicad/-/issues/14460), introducing this new bug.  And was finally solved by commit [7843e6a709](https://gitlab.com/kicad/code/kicad/-/commit/7843e6a70904e9960114a0dc6cfff816b27c116f)
4. The code doesn't compile for the Debian 11 wxWidgets. Now fixed, see KiCad commit [69989e4e64](https://gitlab.com/kicad/code/kicad/-/commit/69989e4e641b310cbce17557cd2be718105c8b67).

Workarounds:
1. KiAuto 2.2.5 adds a filter to discard these (bogus) errors 
2. KiAuto 2.2.5 re-opens the closed dialog to save the ERC results
3. pcbnewTransition 0.3.4-4 (NOT UPSTREAM, my fork) patches KiCad to avoid it
4. Is a compilation issue

All the problems are currently solved in the docker images. The issues 1, 3 and 4 are patched in KiCad binaries and the images contain KiAuto 2.2.5, solving 2.

Note: KiCad 7.0.3 release was cancelled, an important bug was discovered just before the release. So we must wait for 7.0.4.

**Comment by laurencedv** [comment]
Thanks for supporting in anycase

**Comment by set-soft** [comment]
Ok, KiCad 7.0.5 is out, passes all the KiBot regression tests (just details in the generated aspect, be careful with projects started with KiCad 7 and justified text, it changed to KiCad 6 rules, so the justification will change).
I updated the docker images, so I'm closing this.
