### ISSUE TITLE
[BUG] Diff KIBOT_TAG parameter does not work as documented

### ISSUE THREAD

**Issue by matthijskooijman** [INTI-CMNB/KiBot#430]
**Describe the bug**
When specifying the commit to diff against with the `diff` output, you can use `KIBOT_TAG`, which is documented as follows:

> Use KIBOT_TAG-n to search for the last tag skipping n tags.

However, in practice it is implemented by taking the most recent tag (based on commit date, I think), and then skipping n commits up from that.

This even means you can end up with a tag that is not even an ancestor of the current commit at all, and also means there is no way to express "the previous tag".

**To Reproduce**
I did some tests in a WIP repository, no time to provide a reduced example now. Maybe later.

**Expected behavior**
As per documentation: kibot should find the most recent tag (ideally limiting to tags reachable from the current HEAD), and then skip n *tags*, not *n* commits.

Alternatively, the current behavior could be defined as correct by updating the documentation. In this case, this feature has limited usefulness, but can still be used to diff against the most recent tag (but not older tags, and only if the most recent tag is also reachable from the current commit).

**Environment (please complete the following information):**
Where are you running KiBot: Ubuntu 22.10, installed kibot 1.6.2 via pip.

**Additional context**
The source of this problem is this line:

https://github.com/INTI-CMNB/KiBot/blob/376915b293e6aab39cd3c3933e1ce1a779cbf351/kibot/out_diff.py#LL273C1-L273C87

It seems reasonable, but the options passed to `rev-list` do not actually work as hoped here. In particular, the `--tags` option does not limit output to tagged commits (that would work perfectly), but instead:

       --skip=<number>
           Skip number commits before starting to show the commit output.

So this just adds more starting points for the rev-list.

I looked through the manpage and it does not seem immediately obvious how to limit output to tagged commits only (but there's a lot of options, so I'm not sure it's impossible yet).

**Comment by set-soft** [comment]
Hi @matthijskooijman !
You are right, the command skips commits, not tags.
I think the above patch fixes the problem. Is not an efficient solution, but I couldn't find a better one.
KiBot now asks for the list of tags (and commits) and filters the ones that are tags. So we count only tags.
I tried it using KiBot repo and it worked. I also found the consequences of tinkering with the submodules by hand ...
