### ISSUE TITLE
[FEATURE] Allow getting a list of defined variants (or run for all variants)

### ISSUE THREAD

**Issue by matthijskooijman** [INTI-CMNB/KiBot#434]
**Is your feature request related to a problem? Please describe.**
I'm building a reusable workflow to generate build output. I want to generate some outputs for all supported variants. I have not currently found a better way to do this that to run kibot multiple times, once for each variant. But to do so, I need to know what variants are supported. These are defined in the YAML already, but there is no "run for all varants" option, so I need to specify them one by one, meaning both the YAML config and the script/workflow that calls kibot has to know the same list of variants. I would like to remove this duplication.

**Describe the solution you'd like**
Some option, such as `kibot --list-variants` that would print the names of each variant (and possibly other details, as long as the format is easy to parse).

Alternatively, an option to run for each variant in turn would also be helpful (but less generic than the current use of `--global-redef` for defining the variant to use).

**Describe alternatives you've considered**
I'm currently using this command to get the variants (but this is obviously not very robust...):

    kibot -l -v 2>&1 | sed -n 's/DEBUG:Parsing variant `\(.*\)`.*/\1/p'

**Comment by set-soft** [comment]
The above patch adds `--list-variants`, for a script also add `--only-names`.
