### ISSUE TITLE
[Feature] Force text variables in silkscreen (or other board layers) update

### ISSUE THREAD

**Issue by matthijskooijman** [INTI-CMNB/KiBot#441]
**Describe the bug**
When using text variables in silkscreen layers (or other board layers), these are not updated when using the `set_text_variables` preflight.

This behavior seems to be partly intentional in KiCad (due to a "do not change layers on board open" policy), it also occurs if you load the project in KiCad itself, change the variable in the schematic editor and then open the board editor - the silkscreen is not updated until you actually open and save the board setup dialog in the board editor. So in a way this might not be a real bug in kibot, but the behavior is quite surprising.

This behavior is being discussed [in this KiCad bug report](https://gitlab.com/kicad/code/kicad/-/issues/14360), where there are also some proposals of changing it. Fixing this in kibot probably depends on what will be decided there (maybe it will be fixed automatically, maybe kibot will need to explicitly call some update variables function - I do not think that exists in the API currently, though I have not looked very closely). In the meanwhile, a workaround could be to remove the cached text variables from the board on load, but (assuming there is no API for this), this involves messing with the board file text contents before passing it to pcbnew, which would be a hack.

**To Reproduce**
Create a board with a text variable in the silkscreen layer. Use the `set_text_variables` preflight to change the variable. Generate output (e.g. `pcb_print`), and see the silksceen has not changed.

**Expected behavior**
The variable should be updated in the silkscreen.

**Comment by set-soft** [comment]
Hi @matthijskooijman !
If this is a KICad *feature* then this isn't a KiBot bug ;-) I'm changing the title.

**Comment by set-soft** [comment]
Ok, I think I found a reasonable solution.
When using `set_text_variables` now KiBot will reset the PCB cache. If you don't use `set_text_variables` they are left unchanged.
You can also choose to always or never reset them.
I think the default is what people expects and the other options gives enough freedom to customize the behavior.

**Comment by set-soft** [comment]
BTW: The API has BOARD members to Get/SetProperties using a wrapper for the STL map template using wxString to wxString.

**Comment by matthijskooijman** [comment]
I've tested this, works as expected for my usecase. Thanks!
