### ISSUE TITLE
[HOW] Multible variants as selector for features 

### ISSUE THREAD

**Issue by MarkusSBS** [INTI-CMNB/KiBot#465]
Hey 

Is it possible to use  multible Variants  in the same output?`

For example if I have a "variant" for every feature:
+Xtal
+USB
+Seriell
Now i want outputs for 

1) Xtal,USB.seriell
2) Xtal
3) Xtal and USB 

The example here is not exactly what i want (https://inti-cmnb.github.io/kibot_variants_arduprog/) becaus you have to define every possible combination.

The output for a single variant just works fine. 
Somethink like this does not: "kibot  -d Docu -g variant=AFE2,ChemFuse -s run_drc,run_erc print_sch print_pcb_pdf report_full report_history report_pcb_svg interactive_bom"

Is there a special syntax or do i miss something

**Comment by MarkusSBS** [comment]
i was expecting something like this out of the KiBoM docu:
`Specify the PCB variant(s). Support for arbitrary PCB variants allows individual components to be marked as 'fitted' or 'not fitted' in a given variant. You can provide muliple variants comma-separated. You can generate multiple BoMs at once for different variants by using semicolon-separation.`

**Comment by set-soft** [comment]
Hallo @MarkusSBS !

I'm not sure if I understand what you want. Are you talking about avoiding more than one call to KiBot?

When you say "AFE2,ChemFuse" you want to get the same as calling KiBot using AFE2 and then calling it again using ChemFuse?

**Comment by MarkusSBS** [comment]
no i want both in one output.

AFE2  assambles R1,R2,R3
ChemFuse assables R4.R5,R5,IC12


now i want a version with the feater AFE2 AND ChemFuse. The output should be contraining R1,R3,R3 R4,R5,IC12

if i want to output only the feature AFE the output should be R1,R2,R3.

If we use the KiBom Syntax this should be  done by

1) kibot -d Docu -g variant=AFE2,ChemFuse
2) kibot -d Docu -g variant=AFE2

**Comment by set-soft** [comment]
Ok, you have to define a variant for this. Lets say something like:

```
  - name: 'AFE2_and_ChemFuse'
    comment: 'Full board'
    type: kibom
    file_id: _USB
    variant: AFE2, ChemFuse
```

Then just use *AFE2_and_ChemFuse* as a variant. Note that some things are easier to model using KiCost variants where you can use regular expressions to match a variant.
