### ISSUE TITLE
Drill file rename failure

### ISSUE THREAD

**Issue by ukoda** [INTI-CMNB/KiBot#47]
I am seeing an error when it appears to be trying to rename a drill pdf file:

  File "/usr/lib/python3/dist-packages/kibot/out_any_drill.py", line 121, in run
    os.rename(k_file, file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/david/Dev/misc/fancontrol/hardware/fancontrol/kibot/pcbfab/fancontrol-PTH-drl_map.pdf' -> '/home/david/Dev/misc/fancontrol/hardware/fancontrol/kibot/pcbfab/fancontrol-PTH_drill_map.pdf'

There is a fancontrol-PTH-drl-drl_map.pdf file present in that folder.

As this is my first time using KiBot so my kibot.yaml file is pretty much everything from the example so that I can get an idea of what the generated output looks like ahead of refining it to my actual needs.  I have attached the full console output and my kibot.yaml files in case they are needed.  Please let me know if there is any additional information needed.
[KiBot_reanme_fail.zip](https://github.com/INTI-CMNB/KiBot/files/5936558/KiBot_reanme_fail.zip)

**Comment by set-soft** [comment]
Thanks for reporting!

The current git code should fix the problem.
