### ISSUE TITLE
[Why?] Found KiCad 5 and KiCad 6 files

### ISSUE THREAD

**Issue by Informaticore** [INTI-CMNB/KiBot#490]
**Describe the bug**
I try to run KiBot with an older project of mine. I opened it with KiCad 7 and saved all files (schematics and pcb). I even re-imported the components and fixed all issues. But somehow KiBot tells me that there are KiCad 5 and 6 Files but I don't know what else to do, the project should be KiCad 7 only.

Error: `ERROR:Found KiCad 5 and KiCad 6 files, make sure the whole project uses one version (kibot - kiplot.py:696)`

I have a debug log with -vvvv here: https://github.com/HomeSmartMesh/nrf52_thread_sensortag/actions/runs/6058804515/job/16441290382

I can not figure out what else to change.

**Comment by set-soft** [comment]
This is a KiCad 5 file: 

[nrf52-sensor-tag.sch](https://github.com/HomeSmartMesh/nrf52_thread_sensortag/blob/main/nrf52-sensor-tag.sch)

And is mixed with the rest of your project
