### ISSUE TITLE
[FEATURE] export kicad project with libs

### ISSUE THREAD

**Issue by hpopols** [INTI-CMNB/KiBot#491]
**Is your feature request related to a problem? Please describe.**
I want to export the whole project including schematics, pcb and project used libs (schematic and PCB, 3D could be nice but not mandatory). In a word : export a minimal working project in a zip file.

My actual use case is for release (client deliverable, peer review, archiving...) where it is not possible/desirable/practical/relevant to share my company whole libraries.

**Describe the solution you'd like**
Actually, I am able to realize this process manually using only the kicad gui following this [post](https://forum.kicad.info/t/plugin-for-archiving-project/43844/5).

It would be very nice to have it done auto-magically in CI/CD through kiauto/kibot.

**Describe alternatives you've considered**
Continue to do it manually ^^'

**Comment by hpopols** [comment]
I am willing to work on it but, before commit to it, I am wondering:
- How hard it would be to implement this?
- Where to start? Kiauto seems to be the closest tool to implement this into. Is there a similar functionality (menu based actions) already implemented in it?

**Comment by set-soft** [comment]
Hi @hpopols !

When using KiCad 7 the schematic and PCB files are "self-contained", the only real problem are 3D models (not very well handled by KiCad).

The `copy_files` output has a special mode to copy the 3D models and save a modified PCB that can use the copied files.

This should solve your problem. The only detail is that running the ERC/DRC will generate errors about the missing libs (KiCad 7 likes to compare the embedded symbols/footprints with the copy in the lib, and using a weak method).

Is that what you need?

**Comment by hpopols** [comment]
Hi @set-soft !

Thank you again for your responsiveness!

Regarding personal use, I largely concur with your perspective. It seems that there is no essential 'information' missing in the 'copy_file' output. Additionally, manually generating the necessary library from the schematic and pcb files doesn't pose significant challenges once you grasp the inner workings of KiCad and how it stores information.

However, the inconsistency between the original KiCad project and its exported counterpart remains a concern for me. I firmly believe that users should reasonably expect the released (exported) version to exhibit the same 'out-of-the-box' behavior as the one available in the repository version through the CI/CD pipeline. One could argue that the exported version should be responsible for generating outputs (ERC, DRC, PDF, Gerbers, etc.) within the CI/CD pipeline, while the 'exported library' could function as a preflight option.

In my specific scenario, releasing a KiCad project that triggers library errors and fails to pass ERC/DRC inspections, despite the CI/CD reports and my own assessments stating otherwise, is simply not viable. This inconsistency issue carries significant practical consequences, as it raises valid questions and concerns among my clients and peer reviewers. Furthermore, these individuals may perceive the delivered package as incomplete or subpar, which is entirely unacceptable.

I firmly believe that implementing this functionality would be advantageous for everyone. If you share this belief and consider the implementation to be reasonably feasible, I would like to give it a try.

What do you think?

**Comment by set-soft** [comment]
Hi @hpopols !
The main problem here is how KiCad tries to compare a symbol/footprint with its lib counterpart. The comparison assumes things that complicates all the process.
I'm not sure about it. You'll get a couple of libs (one with symbols and the other with footprints) whose only purpose is to allow people to run all the ERC/DRC tests. IMHO is much more sensitive to create a project with these checks disabled. So you can run ERC/DRC, but using the generated project.
For KiCad 5 creating the libs (like the cache lib) is needed, but now all the symbols and footprints are inside the files. Generating a copy of them is only needed to allow KiCad to tell you that they are the same.
I don't know, it looks like a silly workaround.

**Comment by hpopols** [comment]
Hi @set-soft !

I appreciate your prompt response and valuable insights.

I'd like to begin by extending my apologies for any confusion that may have arisen from my previous message. Upon further reflection, I've come to realize that there isn't a fundamental flaw in the way things work; rather, the issue lies in the omission of the original libraries in the exported project. When the original libraries are included, the issues are effectively resolved.

Nevertheless, I maintain the belief that relying on an exported library for the release isn't as cumbersome as it may initially appear. It's analogous to distributing a minimal library virtual environment alongside the project, a practice that can be considered beneficial in certain scenarios.

The present situation results in broken links within the KiCad files, which, in my view, is less than ideal for a release. Disabling the ERC/DRC checks to circumvent this issue doesn't seem to be a desirable solution.

To illustrate my idea, I've been contemplating a potential CI/CD build pipeline for this kind of project (It would involve multiple Kibot jobs):
- "Test the original project": ERC/DRC the original project
- "Process Preflight modification" : do all the pre-flights (including export libs) creating the "modified project"
- "Test the modified": ERC/DRC the modified project
- "Build the outputs": build the project outputs from the modified project including packaging the modified project

I'm interested in hearing your thoughts on implementing such a feature in Kibot. Additionally and in any case, if you could provide some insight into the level of complexity involved and suggest where I should begin (e.g., modifying the PCB/SCH source or working with Kiauto), it would be greatly appreciated.

Once again, thank you for your time and assistance.

Xavier

**Comment by set-soft** [comment]
> I'm interested in hearing your thoughts on implementing such a feature in Kibot.

It can be done without exporting any lib. If the generated project just disables the "lib parity checks" (as other silly things are disabled ... like checking if each symbol has a SPICE model!) you can check the ERC/DRC of the generated project.

> Additionally and in any case, if you could provide some insight into the level of complexity involved and suggest where I should begin (e.g., modifying the PCB/SCH source or working with Kiauto), it would be greatly appreciated.

The KiAuto solution is interesting, but I think will be limited to some KiCad versions. And the code already does some work with libs, specially on KiCad 5 files. So I think adding some functionality to the v5_sch.py and v6_sch.py files will make it simple.

**Comment by hpopols** [comment]
Hi @set-soft !

> It can be done without exporting any lib. If the generated project just disables the "lib parity checks" (as other silly things are disabled ... like checking if each symbol has a SPICE model!) you can check the ERC/DRC of the generated project.

I had a quite relevant experience to share which occurred just this afternoon during a formal design review session with a client. Right at the outset of the session, the client's first step was to meticulously verify the ERC/DRC rules and run both checks on the project I had provided. I was relief to have provided him the project with the exported the libs. I just can say, this practice is standard procedure among my clients and is an integral part of their formal review process.

> The KiAuto solution is interesting, but I think will be limited to some KiCad versions. And the code already does some work with libs, specially on KiCad 5 files. So I think adding some functionality to the v5_sch.py and v6_sch.py files will make it simple.

Thank you for this starting point, I will dig into it and I will stop bothering you with this!

Have a great day!

**Comment by set-soft** [comment]
Hi @hpopols !

The above patch adds a new `source_type` named `project`, I think it covers this feature request. Can you test if this works for your projects?

**Comment by hpopols** [comment]
Hi @set-soft !

Wow this would be amazing! I want definitely check this but I am not sure how to apply this patch inside my container and from which version I should apply it.

Is the last dev kicad7_auto_full container has this feature in it? (https://github.com/inti-cmnb/kicad_auto_test/pkgs/container/kicad7_auto_full/151698440?tag=dev_1.6.4-2bc3bdf_k7.0.9_d12.1_b3.5.1)?

Thank you very much!

**Comment by hpopols** [comment]
Strangely enough the ERC does not report this GND power symbol at all (but it does report a custom transformer symbol which I pin-swaped coils).

I rolled back the project from the previous state, run the same kibot command and the process succeeded. However I have few things to mentions:

- [schematic] The drawing sheets are not copied and rereferenced (.kicad_wks)
- [schematic] There is brand 7 new ERC warnings. All of them are "symbol not found in library" although only 2 unique ones (namely BAT54S and the 74AHC1G14). Both was not reported at all by the erc before, are from the kicad stock lib and are indeed missing from the exported project libraries. I think these 2 stock kicad lib symbols was changed between kicad bugfix versions upgrade and are no more in sync with the schematic but not reported by the ERC. I think these out-of-sync symbols has to be exported to allows kicad to make the comparison and replicate the initial project behaviors.
- [pcb] Custom rules are not copied and rereferenced (.kicad_dru)
- [pcb] I had to turn off the `download` 3D model to avoid all the lib warnings during drc but the 3D model is now out of sync with the source project (but much lighter 😉!). AFAIK, I guess there is nothing you can do about it as you can't change where the `${KICAD6_3DMODEL_DIR}` point to from the project files...

The last point does not bother me as we already planned to be more self contained with all the libraries as you suggest in your documentation.

Note : all the below tests was done using the kicad gui shipped in the container to avoid to many versions/os compatibility problems...

Thank you again

**Comment by set-soft** [comment]
> * [schematic/pcb] The drawing sheets are not copied and rereferenced (.kicad_wks)

This should be fixed.

> * [schematic] There is brand 7 new ERC warnings. All of them are "symbol not found in library" although only 2 unique ones (namely BAT54S and the 74AHC1G14). Both was not reported at all by the erc before, are from the kicad stock lib and are indeed missing from the exported project libraries. I think these 2 stock kicad lib symbols was changed between kicad bugfix versions upgrade and are no more in sync with the schematic but not reported by the ERC. I think these out-of-sync symbols has to be exported to allows kicad to make the comparison and replicate the initial project behaviors.

I need a small example showing it. From the description I don't know what is the source of the problem.

> * [pcb] Custom rules are not copied and rereferenced (.kicad_dru)

Should be fixed.

> * [pcb] The 3D model path between the lib and the pcb are now out of sync. Indeed the exported lib `model` path point to the old `${KICAD6_3DMODEL_DIR}` and not the new 3DMODEL path.

Strange, should be easy to reproduce, an example could help.

**Comment by hpopols** [comment]
I will try to produce you a minimal representative example by tomorow

**Comment by set-soft** [comment]
> > * [pcb] The 3D model path between the lib and the pcb are now out of sync. Indeed the exported lib `model` path point to the old `${KICAD6_3DMODEL_DIR}` and not the new 3DMODEL path.
> 
> Strange, should be easy to reproduce, an example could help.

I took a look at the test project and I don't get this problem. It could be related to some problem trying to detect *KICAD6_3DMODEL_DIR*.
