### ISSUE TITLE
[FEATURE] Gerber X3 Support

### ISSUE THREAD

**Issue by schneider-engineering** [INTI-CMNB/KiBot#500]
**Is your feature request related to a problem? Please describe.**
Gerber X3 Position/Component export does not seem to be supported. (Or I could not find out how to enable it).

**Describe the solution you'd like**
We would like to be able to export Gerber X3 Position files.

**Additional context**
See below screenshots for how to export gerber X3 files. Despite having the term "gerber" in the name, in KiCad it is placed in "Component Placement". 

<img width="578" alt="context_menu" src="https://github.com/INTI-CMNB/KiBot/assets/1207503/49f3c54b-6a16-4388-a00f-e191b89e0f9c">
<img width="791" alt="generate_placement_files" src="https://github.com/INTI-CMNB/KiBot/assets/1207503/0a592860-4b79-40cb-9127-69b0b59193ae">

Any help on this would be appreciated.

**Comment by schneider-engineering** [comment]
A colleague just noticed that kicad-cli actually supports x3 export already:
`kicad-cli pcb export pos --format gerber --use-drill-file-origin --side front`
`kicad-cli pcb export pos --format gerber --use-drill-file-origin --side back`

Would it be possible to include this in KiBot?

**Comment by set-soft** [comment]
Hi @schneider-engineering !

I'm adding some experimental support using the *kicad-cli* interface.
It is available on the _dev_ branch, you can try the *kicad_auto_full:dev* docker image.
Is really experimental: new to KiBot and KiCad itself says is experimental.
The command line help is wrong, your example helped to clarify it! Reading the help it says:

```
 --side                 	Valid options: front,back,both. Gerber format only supports "both". [default: "both"]
```

But for gerber you *must* specify a side, *both* isn't supported. Then it says:

```
--use-drill-file-origin	Use drill/place file origin (ascii or csv only)
```

But is also supported for gerbers, as you show in your example, and this option is the default KiCad behavior for other position files.

Can you try this functionality and let me know if the generated files are correct?
BTW: are you using them for some particular manufacturer or for some particular machine?
