### ISSUE TITLE
[BUG] "Exclude from Bill of Materials" Still Included In the BOM

### ISSUE THREAD

**Issue by dbeckwith01** [INTI-CMNB/KiBot#522]
**Describe the bug**
I am using the docker image for KiBoT on a MacBook M2 Pro to automate my fabrication outputs.  I have noticed the when the "Exclude from Bill of Materials" is ticked in the schematic file it still  shows up in the BOM.

I have posted this [issue](https://github.com/SchrodingersGat/KiBoM/issues/194) on KiBOM initial and I was asked to repost here.

**To Reproduce**
Using docker via `docker run --rm -it -v ./:/src setsoft/kicad_auto:ki7 /bin/bash`
Run KiBot with the following command `kibot -c ./src/config.kibot.yaml -e ./src/Test.kicad_sch  -b ./src/Test.kicad_pcb`

**Expected behavior**
If "Exclude from Bill of Materials" is ticked, the part is not listed in the BOM.

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow? In docker on local machine and also via GitHub
- In a GitHub action? Which tag are you using? Using v2_k7 with GitHub action
- Using a docker image? locally kicad_auto:ki7
- Using a desktop system? MacBook M2 Pro, running MacOS Sonoma v14.0, running docker with Rosetta2

**Additional context**
[Test.zip](https://github.com/INTI-CMNB/KiBot/files/13505955/Test.zip)

**Comment by set-soft** [comment]
Updated docker images should be available now. Let me know if you have any problems

**Comment by dbeckwith01** [comment]
@set-soft Thank you for looking into this, discovering the issue and providing the diff.  What's the best way to implement this fix given that I'm using the Docker images.  I guess I should wait until KiBoM is updated and then the KiBoT image can be updated.

**Comment by set-soft** [comment]
Hi @dbeckwith01 !

I updated the docker images. The KiBoM package should be 1.9.1-2, try pulling fresh images and run:

```
$ dpkg -l kibom*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name            Version      Architecture Description
+++-===============-============-============-==========================================
ii  kibom.inti-cmnb 1.9.1-2      all          Configurable BoM generation tool for KiCad
```
