### ISSUE TITLE
[FEATURE] Parameter for JLCPCB template for plotting footprint values

### ISSUE THREAD

**Issue by gcormier** [INTI-CMNB/KiBot#523]
[      plot_footprint_values: false](https://github.com/INTI-CMNB/KiBot/blob/8bc7ea6324a97b73d489ac850cad87e6110f4635/kibot/resources/config_templates/JLCPCB.kibot.yaml#L39C6-L39C35)

Would it be possible to make this a variable?

I need to set this to `true` for my workflow.

**Comment by set-soft** [comment]
Hi @gcormier !
Please check the implementation is correct

**Comment by gcormier** [comment]
Works great, thanks!
