### ISSUE TITLE
Close the "libraries not found" window.

### ISSUE THREAD

**Issue by dsa-t** [INTI-CMNB/KiBot#54]
I'm trying to use the tool for one of my old projects, but the eeschema becomes stuck at "Not found window":
![image](https://user-images.githubusercontent.com/37658952/109304693-ae7a5600-784d-11eb-80d8-d9d82d5c469e.png)
This window also appears in the normal EEschema, and once it and the "remap symbols" windows are closed, the schematic looks fine.

So I think this window should be closed

**Comment by set-soft** [comment]
You must migrate the project first!
KiAuto tries to workaround a lot od these windows, but these windows:
1) Change from release to release
2) Some are hard to detect because the title is absent or repeated.
You must apply KiBot to projects that you can work with KiCad without extra steps.
