### ISSUE TITLE
[FEATURE] Introduce an '-Werror' like flag (treat warnings as errors).

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#545]
Warnings are great for during development. However in a CI, for releases, going to productions, Warnings should generally not be allowed. A warning is something along the lines of 'look, this is probably not right, but it might work, or not'. For development, this is fine and gives us an incentive to fix things before merging things.

But for releases (e.g. in a CI before merging, or when tagging a release), warnings should generally not be allowed. Compilers traditionally use `-Werror`, treat warnings as errors, to ensure the pipeline blocks.

Note, that there may be a few cases where we still need a mechanism to ignore warnings/errors, before we can handle them all cleanly (e.g. W009 for example).

See https://github.com/INTI-CMNB/KiBot/issues/532#issuecomment-1866202540

**Comment by set-soft** [comment]
Ok, the `-W` option should do it, i.e. 

```shell
$ kibot -W
Using config file: config.kibot.yaml
Using SCH file: light_control.kicad_sch
- 'Exports the PCB to the most common exchange format. Suitable for printing.' (pdf_pcb_print) [pcb_print]
WARNING:(W082) Unknown text variable `date` (kibot.gs - gs.py:439)
ERROR:Warnings treated as errors (kibot.gs - log.py:112)
```
