### ISSUE TITLE
[FEATURE] Consume environment variables to avoid using --define

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#549]
The `--define` option works great, but it would also be great if kibot would consume already existing environment variables, as is common in many tools.

This would allow for having 'global' variables in the environment, but still locally overriding them with the `--define` argument. The big advantage of course is not needing tons of `--define` entries to set, keeping the CLI UI nicer for certain scripted tasks.

**Comment by set-soft** [comment]
The above patch adds a command line option to make it happen
