### ISSUE TITLE
[FEATURE] Introduce additional preflight, which checks schematic and PCB consistency

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#558]
Running the `fab` run, I noticed this mistake in my design. The ERC or DRC did not trigger on this oversight of mine (I forgot to update the PCB.

```
WARNING:(W135) Value field mismatch for `C1` (SCH: `1 µF` PCB: `1µF`) (kibot - kiplot.py:346)
```

Not sure which test checks this, but we should be able to run it pre-flight, just like the erc and drc. I think kicad itself checks 'schematic parity' as part of the DRC, but I don't think it triggers on this.

To be able to run a linting job, for erc, drc, and 'misc' (or make this part of either/both) would be a warm welcome.

**Comment by set-soft** [comment]
This should be covered by the `update_xml` pre-flight, which has a `check_pcb_parity` option. I know is somehow hidden, but the `run_drc` pre-flight clearly explains it.
