### ISSUE TITLE
[FEATURE] KiCad v8 support (DRC/ERC preliminarly)

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#576]
KiCad 8 is just around the corner (RC2 was release just last week), though the end of january deadline has lapsed.

With v8, one exciting new feature is ERC/DRC can be now called from the CLI, and produces JSON output.

Would be great if KiBot would migrate to v8 support, so we don't have to use the KiCad GUI, and video capture, to get ERC and DRC results!

**Comment by oliv3r** [comment]
Well it is just an RC for now :( but that's sad. Was hoping we could get away with the record desktop functionality :(

So lets see if they can fix things before 8.0 gets released!

**Comment by set-soft** [comment]
16965 was fixed, but even the GUI is full of bugs, exclusions not always work, stray messages about locks, really poor performance if pcbnew open eeschema to do the schematic parity check, schematic parity check always performed in the CLI, etc. 

Needs much more work, is not a "release candidate"

**Comment by set-soft** [comment]
Now 16964 is fixed too. So now KiAuto supports E/DRC using *kicad-cli*

I found another bug, related to the exclusions: [17004](https://gitlab.com/kicad/code/kicad/-/issues/17004)

**Comment by set-soft** [comment]
Ok, KiCad 8 should be supported by the current *dev* images.

It uses the CLI for ERC and DRC. 

Needs testing

**Comment by set-soft** [comment]
And now we have new preflights named `erc` and `drc`.
They are for KiCad 8 and has more functionality and less bizarre stuff.
You can even get a report in HTML format.
