### ISSUE TITLE
Unable to access the documentation

### ISSUE THREAD

**Issue by LeanderGlanda** [INTI-CMNB/KiBot#577]
A few days ago the documentation was in the Readme file. Now it's gone there and you can find a link to ReadTheDocs, but that link leads to nowhere and i get a 404 error. I guess this is not how it should be?

For now I'll view the docs in the commit history. If anyone else misses the docs right now, here is a link to the old Readme:
https://github.com/INTI-CMNB/KiBot/blob/caad9ed862cdd9b6c650d6d4669652e15ced087b/README.md

Here a screenshot of the 404 error:
![grafik](https://github.com/INTI-CMNB/KiBot/assets/43491970/99110cd2-5b34-4a0c-b928-366b06bf80ec)

**Comment by Nudelsalad** [comment]
Use this in meantime [Link](https://kibot.readthedocs.io/en/latest/index.html)

**Comment by set-soft** [comment]
Thanks @LeanderGlanda !

I had to change *stable* to *master*, the former didn't work, and forgot to change the link.

The link provided by @Nudelsalad is right, thanks. But will be updated to the dev stuff, so better use the https://kibot.readthedocs.io/en/master/ link
