### ISSUE TITLE
Expansions in dir

### ISSUE THREAD

**Issue by fabiodl** [INTI-CMNB/KiBot#58]
Thank you for the awesome work. More a feature request than an issue. 

`outputs:
  - name: 'gerbers'
    comment: 'gerbers'
    type: gerber
    dir: gerber/%i`

creates a folder named %i instead of applying the expansion

**Comment by set-soft** [comment]
Hi @fabiodl !

Was much more complex than what I thought.
Please test it and report how is working.

**Comment by fabiodl** [comment]
Works like a charm, thank you!
