### ISSUE TITLE
[FEATURE] Add a menu to navigate

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#582]
The navigate web output is pretty nice, but feels a bit empty. A page-header would be nice, that would always be visible, Could contain a title, some background color, and the link to the repo/git-hash (though the trick kikit-present uses, with git origin, doesn't really work).

Further more, a menu navigation bar on the left would also be useful, to help with navigating around the site.

Obviously this feature request is low-priority, but while navigate is super cool, it's a bit nakid.

**Comment by set-soft** [comment]
Hi @oliv3r !
I added some header and a navigation bar. 
You can see it [here](https://set-soft.github.io/kibot_variants_arduprog_site/Browse/t1-navigate.html)
Sure it needs more, but is a good starting point.
Someone with better understanding of HTML+CSS+JavaScript could help to get it working better.
One problem I faced is the "modern" mechanism used for headers, in the old days I could just use frames and get it working perfectly, but they are completely deprecated. I don't like the current recommendations, and I couldn't get it working 100% satisfactorily, when  you visit some link from the navbar you get scrolled with an offset.

If you want to suggest addition/changes do it only with proposed solutions.
