### ISSUE TITLE
[WHY] kiri dies looking for component with UUID (xxx)

### ISSUE THREAD

**Issue by vermut** [INTI-CMNB/KiBot#583]
Same setup as #578

```
> ghcr.io/inti-cmnb/kicad7_auto:dev kibot kiri
...

- Updating BoM in XML format
- 'Generates an interactive web page to browse the schematic and/or PCB differences between git commits.' (kiri) [kiri]
ERROR:While loading `/tmp/tmpbj5mcrmq/Hardware/OpenMowerMainboard/OpenMowerMainboard.kicad_sch` (kibot.gs - gs.py:812)
ERROR:Error looking for component with UUID `/00000000-0000-0000-0000-000061080954/d62697d1-c5d8-427b-abf9-e6b18eb25e79` (kibot.gs - gs.py:812)   
```

**Comment by set-soft** [comment]
Your schematic seems to be broken. 

Take a look at the ecd51c4 commit, you'll see that *OpenMowerMainboard.kicad_sch* defines **SW1** from *RaspberryPi* like this:

```
    (path "/00000000-0000-0000-0000-000061080954/d62697d1-c5d8-427b-abf9-e6b18eb25e79"
      (reference "SW1") (unit 1) (value "MK-11C04-G013") (footprint "lcsc:SW-SMD_MK-11C04-G013")
    )
```

Where *00000000-0000-0000-0000-000061080954* is the *RaspberryPi* sheet:

```
  (sheet (at 223.52 181.61) (size 42.545 22.86) (fields_autoplaced)
    (stroke (width 0) (type solid) (color 0 0 0 0))
    (fill (color 0 0 0 0.0000))
    (uuid 00000000-0000-0000-0000-000061080954)
    (property "Sheet name" "RaspberryPi" (id 0) (at 223.52 180.8984 0)
      (effects (font (size 1.27 1.27)) (justify left bottom))
    )
    (property "Sheet file" "RaspberryPi.kicad_sch" (id 1) (at 223.52 205.0546 0)
      (effects (font (size 1.27 1.27)) (justify left top))
    )
```

But the *RaspberryPi* sheet doesn't contain it. I guess this is a partial commit. 

If you ignore this error and continue you get another error about a missing sub-sheet. So I guess your repo has more than one inconsistent commit.

I found *imu.kicad_sch* was missing in various commits: 
- 4cc18ecebea6186babdc50eb2b9107d6bd6e41d5
- e6af8fcf7297b254ef634621844dbc7e35d5456f
- 632347d0b308ea6f207498d2d4ac6d8f32b6ddb3
- b533e9eda50f7f978beb18727e4410fb0e8e52e9
- d9d065120feb4624123d8615ead9b812b3720b2b
- 2eb79dbfa1c81c9f4eed3e3a5810b4fd66fd4451
- 0c984d98b7a8f0ca9bedb75a2ef9a710e08a96c2
- c921ae3da8d9d19c80b6c40b40ecefa2b0bc3143
- 2a08ab57b31f19dddeda0baa9a8b330bbffba61d
- 0cc361ad114916e72a2947727a987be1702200a5

And around 6673981 the project seems to be using a private submodule that can't be updated without a user/password.

I suggest limiting the KiRi run to just a few commits, not all of them.

I'll commit a patch to continue on errors, but this won't solve the errors ;-)
