### ISSUE TITLE
Use kicad_dnp in Pick & place

### ISSUE THREAD

**Issue by hardwaremaker** [INTI-CMNB/KiBot#605]
Currently, the output type "position" does not recognize the kicad dnp flag. Would be very helpful to have this option.

**Comment by set-soft** [comment]
Please elaborate, currently you must apply a filter in order to get components filtered. And if you apply filters then the following option controls the KiCad DNP flag:

```python
            self.kicad_dnp_applied = True
            """ The KiCad v7 PCB flag *Do Not Populate* is applied to our fitted flag before running any filter """
```

Do you want an option to make it happen even when no filters are applied?
Note that currently any filter will do the work:

```python
def reset_filters(comps):
    logger.debug('Filters reset')
    for c in comps:
        c.included = True
        # If the global kicad_dnp_applied variable is True try to copy the DNP flag from KiCad v7
        c.fitted = not GS.global_kicad_dnp_applied or c.kicad_dnp is None or not c.kicad_dnp
        c.fixed = False
        c.back_up_fields()
```
