### ISSUE TITLE
[FEATURE] Add option to disable drawings rendering in render_3d

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#614]
With kibot 1.6.6., KiCAD8 the User.Drawings are rendered, which gives unexpected black lines:

![image](https://github.com/INTI-CMNB/KiBot/assets/1504752/a3b19fbe-7643-472f-92c5-80f0de632e8a)

The layer was disable in my GUI.

Maybe there is a way to disable this - IHMO this can be inactive by default and potentially be controlled with an option such as `show_drawings` similar to `show_silkscreen`.

**Comment by set-soft** [comment]
Note that this is huge change in KiCad behavior.

KiCad 7:
- Only one option for comments and drawings
- Only one option for eco 1 and 2
- Comments, drawings, eco 1 and eco 2 **NOT** displayed when using realistic colors

KiCad 8:
- Separated options for comments and drawings
- Separated  options for eco 1 and 2
- Comments, drawings, eco 1 and eco 2 displayed when using realistic colors
- Default is to show them if no option is found in the JSON file

**Comment by mdeweerd** [comment]
Thank you for the feedback - that does imply a few changes.

I'ld be find by adding what is needed to "the JSON file".  However, I only find notifications.json in the root of the local kicad directory on windows, and packages.json, repository.json in the pcm subdirectories.

I've gone through the preferences for the 3D settings but did not find anything related.

But because I am using docker I guess I need to bind a json file when running in docker.

**Comment by set-soft** [comment]
I'm adding the relevant options to KiAuto, but I found KiCad 8 did other changes related to colors

**Comment by set-soft** [comment]
The above patch adds more control about what KiCad 8 draws. Needs KiAuto 2.3.1 and should avoid user drawings (added by default by KiCad when the JSON config doesn't explicitly disable them!)

But note that I'm deprecating this output in favor of the Blender output. The KiCad developers said they don't like the idea of having the 3D render in `kicad-cli` and the behavior of the GUI changes all the time. The 3D render isn't intended to be non-interactive.

To show you just one detail, here is the same test case using different KiCad versions:

![drawings_layer](https://github.com/INTI-CMNB/KiBot/assets/22823627/3e11cfb0-8c93-4056-a21a-24288e9d5b91)
![drawings_layer](https://github.com/INTI-CMNB/KiBot/assets/22823627/cd5df74b-acd5-4774-88fb-250e462da7c0)
![drawings_layer](https://github.com/INTI-CMNB/KiBot/assets/22823627/c4f2a32f-b9fb-4d00-82f9-9493be365810)
![drawings_layer](https://github.com/INTI-CMNB/KiBot/assets/22823627/81380803-9c54-447e-a58a-bc1640d477d0)

Or using the "realistic" mode:

![drawings_real](https://github.com/INTI-CMNB/KiBot/assets/22823627/019b0e14-e2b6-427c-b564-b2e3dad70c7b)
![drawings_real](https://github.com/INTI-CMNB/KiBot/assets/22823627/b793d7f3-e8ee-485a-bb54-b20caf4383e3)
![drawings_real](https://github.com/INTI-CMNB/KiBot/assets/22823627/ea8cddb9-68f7-4182-ba5f-5e02a588ca6d)
![drawings_real](https://github.com/INTI-CMNB/KiBot/assets/22823627/638f762c-46a4-4b62-8eb2-5de34d4cf2ce)

**Comment by mdeweerd** [comment]
I understand that he 3D render is changing accross versions.
Even if not interactive, the 3D snapshot gives a better idea about the depth of components vs. the 2D image (=orthogonal 3D) which is also created using the same method so I guess it would suffer from the same issues.

The 2D image is useful to compare with the real board.  I hope that this is not deprecated.

**Comment by set-soft** [comment]
Try using an *orthographic* camera in Blender to get a pseudo-2D image.

The deprecation means that I won't give priority to this output, and won't worry much if it has errors or limitations.

If something is missing in the Blender Export output we should add it, but we can't currently rely on the KiCad renderer, and this is the opinion of the KiCad developers.
