### ISSUE TITLE
Erroneous "Malformed Component Reference" Error 

### ISSUE THREAD

**Issue by sphawes** [INTI-CMNB/KiBot#626]
Hey there! Having an issue with exporting a board last saved in KiCad 8. Apologies in advance if this is user error, and not an actual bug!

**Describe the bug**
When trying to export a 4 layer board generated with KiCad 8, I get a `Malformed component reference 'SYMBOL' (kibot.gs - gs.py:834)` error. There is no component reference with the value "SYMBOL" in the board.

**To Reproduce**
The Github Action workflow YAML file is [here](https://github.com/opulo-inc/lumenpnp/blob/main/.github/workflows/export-ecad.yaml). It seems to be failing on [this board](https://github.com/opulo-inc/lumenpnp/tree/main/pnp/pcb/mobo). The KiBot config is [here](https://github.com/opulo-inc/lumenpnp/blob/main/.github/workflows/scripts/kibot/config-4layer.kibot.yaml).

**Expected behavior**
I expected it to export the board.

**Screenshots**
Below is a screenshot of the error.
![Screenshot 2024-05-24 at 3 47 11 PM](https://github.com/INTI-CMNB/KiBot/assets/1865862/f76b35a9-3a31-49cd-aa8f-7671ddca037f)

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow? (Ex: `GitHub`/`GitLab`)
  - Github Actions
- In a GitHub action? Which tag are you using? (Ex `v1`, `v1_k6`, `v2`, `v2_d`, `v2_dk6`, `v2_k6`)
  - N/A
- Using a docker image? (Ex: `kicad_auto:ki6`, `kicad_auto:latest`, `kicad_auto:dev`, `kicad_auto:dev_k6`, a custom one? can you provide the `Dockerfile`)
  - I tried a few images. I tried `container: ghcr.io/inti-cmnb/kicad8_auto:1.6.5`, `container: ghcr.io/inti-cmnb/kicad_auto_full:dev_k8_1.7.1-deaed3c_k8.0.2_d_sid_b3.5.1`, and `container: ghcr.io/inti-cmnb/kicad_auto:latest`.
- Using a desktop system? Which OS, distro and version?
  - N/A

**Additional context**
I hunted through the files I'm giving to KiBot and couldn't find a component reference called "SYMBOL" and I tried to diagnose what the problem was based on the error code but wasn't able to figure it out. I'm guessing this is a KiCad 8 compatibility issue, but wasn't sure!

I'm sorry if I'm merely doing something wrong, and this isn't actually a bug. Thank you for maintaining such a wonderful piece of software!

**Comment by set-soft** [comment]
> There is no component reference with the value "SYMBOL" in the board.

Well ... you have it:

![image](https://github.com/INTI-CMNB/KiBot/assets/22823627/10af6a5b-3d85-467c-a155-548e6000e99e)

And you also have one that says **LOGO** and another that says **GOBLIN** ;-)

I don't know why the KiCad "Find" fails to find them, but they are there
