### ISSUE TITLE
[BUG] BlenderLightOptions object is not iterable

### ISSUE THREAD

**Issue by N0cynym** [INTI-CMNB/KiBot#630]
**Describe the bug**
Blender export failed with a development image > Version 1.7.0

```
File "/usr/local/lib/python3.11/dist-packages/kibot/out_blender_export.py", line 392, in config
    for li in self.light:
TypeError: 'BlenderLightOptions' object is not iterable
Uploading artifacts for failed job
Uploading artifacts...
WARNING: Production/Images/: no matching files. Ensure that the artifact path is relative to the working directory (/builds/sl3/test) 
ERROR: No files to upload                          
Cleaning up project directory and file based variables
ERROR: Job failed: exit code 1
```

**Environment**

- In a CI/CD workflow (`GitLab`)
- [dev_1.7.1-96837d0_k7.0.11_d12.1_b3.5.1 ](https://github.com/inti-cmnb/kicad_auto_test/pkgs/container/kicad7_auto_full/230248836?tag=dev_1.7.1-96837d0_k7.0.11_d12.1_b3.5.1)

**Comment by set-soft** [comment]
The above patch should solve the problem

Thanks for reporting!
