### ISSUE TITLE
Windows PWD module not supported

### ISSUE THREAD

**Issue by kontakt** [INTI-CMNB/KiBot#635]
Fill as much as you can, remove the rest

**Describe the bug**
Kibot does not run on Windows

**To Reproduce**
Kibot run in Kicad shell

**Screenshots**
WARNING:(W106) Running on Windows, this is experimental, please report any problem (kibot - log.py:108)
ERROR:Unable to import plug-ins: No module named 'pwd' (kibot.gs - __init__.py:1518)
ERROR:Make sure you used `--no-compile` if you used pip for installation (kibot.gs - __init__.py:1518)
ERROR:Python path: ['C:\\Users\\-\\Documents\\KiCad\\8.0\\3rdparty\\Python311\\Scripts\\kibot.exe', 'C:\\Program Files\\KiCad\\8.0\\bin\\DLLs', 'C:\\Program Files\\KiCad\\8.0\\bin\\Lib', 'C:\\Program Files\\KiCad\\8.0\\bin\\Lib\\site-packages', 'C:\\Users\\-\\Documents\\KiCad\\8.0\\3rdparty\\Python311\\site-packages'] (kibot.gs - __init__.py:1518)

**Environment (please complete the following information):**
Where are you running KiBot:
Windows 11

**Comment by set-soft** [comment]
Hi @kontakt !
The above patch should solve the issue.
Thanks for reporting!
