### ISSUE TITLE
Integrate InteractiveHtmlBom

### ISSUE THREAD

**Issue by CameronBrooks11** [INTI-CMNB/KiBot#658]
Integration of the InteractiveHtmlBom functionality either as part of docs index or perhaps on the top level of pcb index.

**Comment by set-soft** [comment]
I'm not sure what you want. The *ibom* output implements InteractiveHtmlBom. 

In the web page generated by *navigate* you'll find it under **Schematic/BoM** and **PCB/fabrication/assembly**. This is the default *category*, which can be customized.

**Comment by CameronBrooks11** [comment]
Thanks for the info...I was trying things about for the first time and did a skim of the source and must've missed that

**Comment by set-soft** [comment]
You can find a full list of supported outputs [here](https://kibot.readthedocs.io/en/master/configuration/outputs.html#supported-outputs)

**Comment by CameronBrooks11** [comment]
That’s great, thank you so much!
