### ISSUE TITLE
[BUG] populate: highlighting rectangle for components soldered in the bottom can be wrong when using "render_3d" as renderer

### ISSUE THREAD

**Issue by dhaillant** [INTI-CMNB/KiBot#659]
Hi,
With kibot v1.7.0, I'm encountering a problem using pcbdraw/populate: the red highlighting rectangle is oriented in the wrong direction, 180° from expected orientation.

As far as my tests go, the problem seems to happen only on the back side view.

Also, the problem seems to happen with any component on the PCB back side, but is only visible when the footprint has its anchor point not in the middle, but rather located on a corner, for example on pin 1.

**To Reproduce**
In PCB editor, add to the rear side of the PCB a footprint with its anchor not centered (typically, anchor on pin 1), or use the demo project included below.
Then generate the populate document with `make populate`.

Check the results at "kibot/Populate/index.html"

**Screenshots**
![2024-09-12_12-36-15](https://github.com/user-attachments/assets/0c53fd0c-0e71-418a-b8fd-d82c047da741)
![2024-09-12_12-35-48](https://github.com/user-attachments/assets/6dcb1b53-a3b7-430a-9b73-8dc0b4b70ec8)
![2024-09-12_12-35-29](https://github.com/user-attachments/assets/9a8a9dec-85c6-4d4c-9c74-761075e4c8a5)
And when I move the anchor point of the DIP package:
![2024-09-12_13-18-27](https://github.com/user-attachments/assets/99d65687-ac61-4d94-8db2-67ebe27f0915)

**Environment:**
Kibot v1.7.0 installed from kibot_1.7.0-1_all.deb
used with call to makefile

Application: KiCad x86_64 on x86_64

Version: 7.0.11-7.0.11~ubuntu22.04.1, release build

Libraries:
	wxWidgets 3.2.1
	FreeType 2.11.1
	HarfBuzz 6.0.0
	FontConfig 2.13.1
	libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.18

Platform: Ubuntu 22.04.4 LTS, 64 bit, Little endian, wxGTK, xubuntu, x11

** other info **
Renderer used is "render_3d".

This bug was previously reported at https://github.com/yaqwsx/PcbDraw/issues/175

[populate_orientation.zip](https://github.com/user-attachments/files/16978401/populate_orientation.zip)

**Comment by set-soft** [comment]
Thanks for reporting. KiCad does some particular transformation for components in the bottom side of the PCB.
The above patch solves the issue.

Note that the *render_3d* output doesn't use PcbDraw. Also note that currently we use an embedded copy of PcbDraw instead of the official one (the code diverted).

The patch is available in the *dev* branch/images
