### ISSUE TITLE
kicost ist not recognized as a valid output

### ISSUE THREAD

**Issue by ilyazilberman** [INTI-CMNB/KiBot#66]
I am running KiBot on the docker container: setsoft/kicad_auto:latest, which has KiCost v1.1.5 installed. My config.kibot.yaml file includes the following output:
    ` - name: kicost`
    `  comment: "KiCost of non JLC components"`
    `  type: kicost`
    `  options:`
    `  currency: EUR`

Unfortunately, it produces the following error:
`ERROR:Unknown output type: `kicost` (kibot.kibot.error - error.py:40)`

**Comment by set-soft** [comment]
Hi @ilyazilberman !
The KiCost support isn't included in the last release: v0.10.1
You need the git code for this. You can add a `git clone` to your pipeline and then run the KiBot from the cloned repo (*path_to_repo*/src/kibot).  No installation needed.
This is similar to what is done by the regression tests, that are currently testing the KiCost functionality.

BTW, I'm trying to integrate the KiCost spreadsheet with the one generated by the `bom` output.
