### ISSUE TITLE
ibom extra_fields and xml

### ISSUE THREAD

**Issue by scottbez1** [INTI-CMNB/KiBot#68]
Awesome project! I ran into a small hiccup when first setting this up where I was getting cryptic error messages when I attempted to use `extra_fields` with ibom outputs. It turns out that it relies on the bom xml to pull those extra fields, which I don't normally generate, so the fix was to add `update_xml` to the preflight. It might be nice if `extra_fields` automatically set `update_xml` to true, or perhaps just print an error/warning if `extra_fields` is set without `update_xml`?

It also seemed like the `netlist_file` was defaulting to the working directory path instead of the xml file; not sure if this is intentional or if it would be possible/reasonable to default to '%F.xml' instead?

Separately, but kind of related to my debugging process for this issue, is there a way to enable verbose output via the [github action](https://github.com/INTI-CMNB/KiBot/blob/master/action.yml)? Would be nice to make CI verbose so it's easier to track down failures without having to re-run and reproduce the issue.

Thanks!

**Comment by set-soft** [comment]
Hi @scottbez1 !

> Awesome project!

Thanks!

> I ran into a small hiccup when first setting this up where I was getting cryptic error messages when I attempted to use `extra_fields` with ibom outputs. It turns out that it relies on the bom xml to pull those extra fields, which I don't normally generate, so the fix was to add `update_xml` to the preflight. It might be nice if `extra_fields` automatically set `update_xml` to true, or perhaps just print an error/warning if `extra_fields` is set without `update_xml`?

I added a warning. I don't like generating the XML *automagically*. This is a slow and complex task (we must start KiCad and interact with the GUI). Is much simpler if the user generates it. The warning suggests both options.

> It also seemed like the `netlist_file` was defaulting to the working directory path instead of the xml file; not sure if this is intentional or if it would be possible/reasonable to default to '%F.xml' instead?

The path thing was an error. Now it properly defaults to nothing. But if we need the netlist and the XML file is there now KiBot passes it to iBoM. I had the (wrong) impression that iBoM tried to get the file by itself.

> Separately, but kind of related to my debugging process for this issue, is there a way to enable verbose output via the [github action](https://github.com/INTI-CMNB/KiBot/blob/master/action.yml)? Would be nice to make CI verbose so it's easier to track down failures without having to re-run and reproduce the issue.

I agree, but I don't know much about its implementation. @nerdyscout implemented it.

I modified it to support `-v N`, but I don't have a test case to check it. Please let me know if it works.
