### ISSUE TITLE
[BUG] PCB Print: hole color in footprints ignored when plotting only copper layer(s)

### ISSUE THREAD

**Issue by nguyen-v** [INTI-CMNB/KiBot#696]
**Describe the bug**
When printing only copper layers (for example only F.Cu, or F.Cu + In1.Cu), `colored_holes` and `holes_color` options are ignored for holes defined in footprints. Hole color is correct when printing copper layers with other non-copper layers (e.g. Margin, User.Comments, F.Courtyard, etc.).

Not a critical issue as I could print the copper layers with an empty non-copper layer, but behavior is certainly not expected.

Example of output:
https://github.com/EPFLXplore/XRE_LeggedRobot_HW/blob/8448cbcd72b614c6eafe8d6ddd7beaad7256eb10/amulet_controller/Generated/Manufacturing/Fabrication/amulet_controller-fabrication_layers.pdf

With the following settings:
https://github.com/EPFLXplore/XRE_LeggedRobot_HW/blob/8448cbcd72b614c6eafe8d6ddd7beaad7256eb10/amulet_controller/kibot.kibot.yaml#L306

**To Reproduce**
`git clone git@github.com:EPFLXplore/XRE_LeggedRobot_HW.git`
`cd ./XRE_LeggedRobot_HW`
`git checkout 8448cbcd72b614c6eafe8d6ddd7beaad7256eb10`
`cd ./amulet_controller`
`kibot -c kibot.kibot.yaml`

**Expected behavior**
Hole colors should follow the `colored_holes` and `holes_color` options, even when plotting only copper layers

**Screenshots**
Only F.Cu plotted:
![image](https://github.com/user-attachments/assets/3c5ef57d-859f-44c9-bfc4-7d917c9a0096)

F.Cu + In1.Cu:
![image](https://github.com/user-attachments/assets/e53b77ba-279a-48bd-9e50-490ddd857c24)

F.Cu + Margin (hole color is correct)
![image](https://github.com/user-attachments/assets/7463a0d0-57b7-49ca-a752-a1cdff6071a1)

**Environment (please complete the following information):**
WSL2 on Windows, running Ubuntu 24.04 LTS. Using the dev branch.

**Comment by nguyen-v** [comment]
Correct behavior when plotting with `frame_plot_mechanism: 'gui'`. Frame is weirdly cut but that should probably be discussed in another issue
![image](https://github.com/user-attachments/assets/2b763a45-d1e1-4b68-9e02-13e85bae2484)

**Comment by set-soft** [comment]
Please avoid mixing things.
About the first: is consequence of a new KiCad "feature" which draws holes in layers that never did (i.e. the Rescue layer)
This new behavior impacted to various plugins and outputs.

**Comment by set-soft** [comment]
The above patch should solve the problem

**Comment by set-soft** [comment]
> Correct behavior when plotting with `frame_plot_mechanism: 'gui'`. Frame is weirdly cut but that should probably be discussed in another issue

I'll suggest trying from the GUI: just print your design to an SVG file and you'll see why you get this.
