### ISSUE TITLE
Malformed wire ERROR

### ISSUE THREAD

**Issue by CristobalFerrer** [INTI-CMNB/KiBot#70]
Hi, 

While using Kibot to generate my project output files I ran into this error:

`ERROR:At line 304 of `/home/cferrer/Desktop/PCBs/safety_switch.sch`: Malformed wire (kibot.kibot.kiplot - kiplot.py:202)
ERROR:Line content: `Wire Notes Line rgb(255, 0, 0)` (kibot.kibot.kiplot - kiplot.py:203)`    

It seems Kiplot doesn't support colored Wire Notes Line/Graphic Polyline.
I traced back the error to line 1174 in the v5_sch.py file, https://github.com/INTI-CMNB/KiBot/blob/1d44a6a5514d4f35d87e5d9b9814bafd3e821786/kibot/kicad/v5_sch.py#L1174-L1176

Because "Wire Notes Line rgb(255, 0, 0)" have an extra argument specifying the line color, the length doesn't match 3. 
I fixed the issue by adding an additional condition:
```     res = _split_space(line)
        if len(res) != 3:
            if len(res) > 3:
                print(res, "rgb" in res[3] or "width" in res[3])
                if not("rgb" in res[3] or "width" in res[3]):
                    raise SchFileError('Malformed wire', line, f)
            else:
                raise SchFileError('Malformed wire', line, f)
```

It would be nice if colored Wire Notes Line would be supported.

**Comment by set-soft** [comment]
Hi @CristobalFerrer !

Thanks for reporting. Didn't know it was posible to change color, width and aspect of "wire notes line".
I added support for it.
Can you test it?

**Comment by CristobalFerrer** [comment]
@set-soft will do, thanks a lot!
And thank you also for the amazing job done with the development of Kibot!
