### ISSUE TITLE
[HOW] Keep PCB setup for panel

### ISSUE THREAD

**Issue by N0cynym** [INTI-CMNB/KiBot#703]
**What do you want to achieve?**

I would like to have untended vias in my panel.
If I create gerbers from my panelized pcb, the `tent_vias` -> `viasonmask` option will be reseted in the panelize output file.

Is there any way of setting `tent_vias` for the panelize tool in the KiBot configuration?

This option is availible in [PDF output](https://kibot.readthedocs.io/en/master/configuration/outputs/PDFOptions.html).

**Comment by set-soft** [comment]
The gerber output also has *tent_vias*: https://kibot.readthedocs.io/en/master/configuration/outputs/GerberOptions.html

**Comment by N0cynym** [comment]
Thanks for this information @set-soft!

Do you think a feature request for the panelize tool makes sense to keep the pcb preferences from the input file for the output file?

**Comment by set-soft** [comment]
Please elaborate, if you use the `gerber` output to generate the gerbers you just need to set the `tent_vias`. 
Are you talking about the GUI when you open the panel?

**Comment by N0cynym** [comment]
Yes I mean the output panel PCB.

The settings in the pcb file are reset to default if I open the board file in the gui.

Would it be possible to copy the board settings from the origin?

**Comment by N0cynym** [comment]
> The gerber output also has _tent_vias_: https://kibot.readthedocs.io/en/master/configuration/outputs/GerberOptions.html

I need to report that this option does not work for KiCad 8 projects with KiBot 1.8.1.

**Comment by N0cynym** [comment]
I created bug report #74

**Comment by set-soft** [comment]
The above patch adds an option to copy the setting after creating a panel.

The default value is *auto* and currently means *yes* for KiCad 8.
