### ISSUE TITLE
directory of kibot_errors.filter

### ISSUE THREAD

**Issue by nerdyscout** [INTI-CMNB/KiBot#71]
Hi @set-soft 

according to the readme the kibot_errors.filters should be created in the output dir.
> Important note: this will create a file named kibot_errors.filter in the output directory.

but, from what I could see, kibot is creating this file in the kicad project dir. As those could be different directories I am currently running into issues.

edit1:
don't know what is going on, now it is fine... seems like directory is is just sometimes broken, i will come back as soon as I could figure out when this happens.

edit2:
ok my latest guess is: when the output directory does not exist creating the kibot_errors.filter fails.

**Comment by set-soft** [comment]
Hi @nerdyscout !
The problem you mention in edit 2 should be fixed in 111b86a3751b4e6466c68fdcc60a48bb427e9f77
Are you using git code?

**Comment by nerdyscout** [comment]
> The problem you mention in edit 2 should be fixed in [111b86a](https://github.com/INTI-CMNB/KiBot/commit/111b86a3751b4e6466c68fdcc60a48bb427e9f77)
thank you for your quick support.


> Are you using git code?
not sure if I got your question right... I am currently depending on your release packages, but would prefer to run on master. But so far I have not been able to figure out how to implement this in my current setup.

**Comment by set-soft** [comment]
The fix isn't released yet.
Using the git code is a simple solution.
I'm working on a new release, including experimental KiCost support.

**Comment by set-soft** [comment]
Hi @nerdyscout !

I released 0.11.0, and the docker images are updated.
This should fix your problem.
