### ISSUE TITLE
[BUG] Worksheet (.kicad_wks) not found by PCB_Print

### ISSUE THREAD

**Issue by BetCvR6** [INTI-CMNB/KiBot#719]
Hi,

I work with docker under Windows 10 and with Kicad v8.0.6.
I use pdf_sch_print and pcb_print to generate pdf files of my design : schematic_frame.kicad_wks for schematic and pcb_frame.kicad_wks for PCB design.
With kibot v1.8.1 I have no problem and all works fine. But with v1.8.2, kibot doesn't find the PCB layout file.
I also tried with last 1.8.3_dev version but I got the same result.
_Just a precision about tree structure : kicad_wks files are placed inside a directory called "template" itself located in project directory. So, files are loaded in relative by Kicad with path as : "template\pcb_frame.kicad_wks"

I used the following command lines in my project directory :
```
docker run -it --rm -v %cd%:/project ghcr.io/inti-cmnb/kicad8_auto_full:1.8.1 /bin/bash
cd project
kibot
```
And I got that:
```
Using config file: test.kibot.yaml
Using SCH file: test_proj.kicad_sch
- Running the ERC
- Running the DRC
- 'Schéma en PDF' (pdf_sch) [pdf_sch_print]
- 'Spécifications PCB' (pdf_pcb) [pcb_print]
Found 0 unique warning/s (3 total, 3 filtered)
```

But with these command lines :
```
docker run -it --rm -v %cd%:/project ghcr.io/inti-cmnb/kicad8_auto_full:1.8.2 /bin/bash
cd project
kibot
```
I got that:
```
Using config file: test.kibot.yaml
Using SCH file: test_proj.kicad_sch
- Running the ERC
- Running the DRC
- 'Schéma en PDF' (pdf_sch) [pdf_sch_print]
- 'Spécifications PCB' (pdf_pcb) [pcb_print]
ERROR:Missing page layout file: /project/template\schematic_frame.kicad_wks (kibot.gs - gs.py:850)
```

It's strange, because it seems kibot uses schematic_frame.kicad_wks instead of pcb_frame.kicad_wks... I made these tests to try to understand what happen :

1. First, I tried to add only pcb_frame.kicad_wks file directly in the project directory but this doesn't work.
2. Then, I tried to add only schematic_frame.kicad_wks file directly in the project directory and it works! But when I open generated pdf files, kibot leven so oaded the right layout for each job.

I think kibot just needs a link to schematic_frame.kicad_wks but it doesn't really use it. I hope these tests help you.

Please find in attachment a test project to reproduce this problem.
[test_proj.zip](https://github.com/user-attachments/files/17735397/test_proj.zip)

Do not hesitate to ask me for additional information if necessary.

Thanks a lot for your work!

**Comment by set-soft** [comment]
Hi @BetCvR6 !

The problem is related to the use of backslashes in file names:

/project/template\schematic_frame.kicad_wks

Backslashes are Windows specific, the low level Windows (and DOS) API supports regular slashes, used by UNIX way before DOS even existed, I don't understand why KiCad allows it, your project uses names invalid for Linux and macOS.

KiBot was already detecting it for schematic printing, but not for PCB printing.

Now it should work for both cases.
