### ISSUE TITLE
Help needed - JLCPCB rotation settings

### ISSUE THREAD

**Issue by stuartpittaway** [INTI-CMNB/KiBot#74]
Hi, great tool/product!

I can see that it supports JLCPCB output options including rotation of parts.

I'm using a "TLP172GM" which has a footprint of "Package_SO:SO-4_4.4x3.6mm_P2.54mm" - this is incorrectly rotated in my circuit board.

I cannot see where to add a rotation configuration/parameter - what file should it go in?

**Comment by set-soft** [comment]
Hi @stuartpittaway !

Please read the following section in the docs:

https://github.com/INTI-CMNB/KiBot#notes-about-the-position-file

If this doesn't work open a more specific issue.
