### ISSUE TITLE
Install on Debian failed due to crude packet version

### ISSUE THREAD

**Issue by bene42** [INTI-CMNB/KiBot#75]
The Debian kicad maintainer mixed up the upload some time ago.
As a result of that incident the version in sid (and bullseye) was changed to "5.99.0+really5.1.10+dfsg1-1".

The installation of the kibot_0.11.0-1_all.deb Package failed with:
---8<---
Traceback (most recent call last):
  File "/usr/bin/kibot", line 16, in <module>
    main()
  File "/usr/lib/python3/dist-packages/kibot/__main__.py", line 286, in main
    detect_kicad()
  File "/usr/lib/python3/dist-packages/kibot/__main__.py", line 244, in detect_kicad
    GS.kicad_conf_path = pcbnew.GetSettingsManager().GetUserSettingsPath()
AttributeError: module 'pcbnew' has no attribute 'GetSettingsManager'
---8<---

The version detection of kibot recognized version 5.99, but kicad is version 5.1.10.
Outwit the version detection and hardcode the version to 5.1.10 work out fine.

**Comment by set-soft** [comment]
Hi @bene42 !

Only sid seems to be affected. No 5.1.10 on bullseye yet.
When you run something like `kibot -vvvv --help-outputs`: are you getting `5.99.0+really5.1.10+dfsg1-1`?

**Comment by bene42** [comment]
Hi @set-soft,

Only sid is affected. Sorry to mention bullseye. As far as I see it would not be affected at all.

```
$ kibot -vvvv --help-outputs
DEBUG:Detected KiCad v5.99.0 (5.99.0+really5.1.10+dfsg1-1 5099000) (kibot - __main__.py:238)
Traceback (most recent call last):
  File "/usr/bin/kibot", line 16, in <module>
    main()
  File "/usr/lib/python3/dist-packages/kibot/__main__.py", line 287, in main
    detect_kicad()
  File "/usr/lib/python3/dist-packages/kibot/__main__.py", line 245, in detect_kicad
    GS.kicad_conf_path = pcbnew.GetSettingsManager().GetUserSettingsPath()
AttributeError: module 'pcbnew' has no attribute 'GetSettingsManager'
DEBUG:Detected KiCad v5.99.0 (5.99.0+really5.1.10+dfsg1-1 5099000) (kibot - __main__.py:238)
```

**Comment by set-soft** [comment]
Hi @bene42 !
I think the last patch will solve the problem.
Please tell me if it works.

**Comment by bene42** [comment]
The patch works and kibot is running fine:

```
$  kibot -vvvv --help-outputs
DEBUG:Detected KiCad v5.1.10 (5.1.10+dfsg1-1 5001010) (kibot - __main__.py:245)
DEBUG:KiCad config path /root/.config/kicad (kibot - __main__.py:281)
DEBUG:Importing from /usr/lib/python3/dist-packages/kibot (kibot.kibot.kiplot - kiplot.py:53)
...
```
Thanks for your work!

**Comment by set-soft** [comment]
> but that leaves me with a corrupt/incomplete kibot installation:

Looks like some mixed installation ... globals.py is part of KiBot and wasn't installed.

**Comment by hoijui** [comment]
works, thank you! :-)
.. wohoo! now al working again. :-)
