### ISSUE TITLE
[FEATURE] Also print position information on W147

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#751]
I just ran into:
```
WARNING:(W147) Not including component `KiKit` in filters because it has a malformed reference (kibot - kiplot.py:334)
```
which was odd, as I _thought_ I just had replaced all refdes's. After some searching in the files (git grep) I found more missing refdes's. This was easy to fix, but frustrating as I thought I had done them all already. It required me to look at the source code and noticed that the actually exception tries hard to also print the position, but the caught exception just prints the above warning.

Could we instead of the current warning not print the output of the exception, which would include the position?

**Comment by set-soft** [comment]
I added the PCB coordinates.
We can't use the value in the *SchError* exception because this is the schematic coordinate, which in this case doesn't exist because this code is adding a component that is in the PCB but not in the schematic.
