### ISSUE TITLE
[XLSX BOM] Add an option for logo size

### ISSUE THREAD

**Issue by fleborne** [INTI-CMNB/KiBot#84]
Hi,

I didn't find how to set the size of the logo with the xlsx BOM (type 'bom'). Did I miss something?

Thanks!

**Comment by set-soft** [comment]
Hi @fleborne !
You can do it by changing the size of the image itself.
The scaling for the image is very tool dependent. What's even worst: the same spreadsheet will scale the logo using some internal rules that are hard to understand.
I can add a scale factor, but I doubt you'll get a good result using OpenOffice. Perhaps Excel can benefit from it.
