### ISSUE TITLE
Add support for variants and filters in import files

### ISSUE THREAD

**Issue by neilenns** [INTI-CMNB/KiBot#88]
JLCPCB has specific requirements for their SMT service BOM files that require a custom filter and variant to produce correctly. I have a dedicated `JLCPCB.kibot.yaml` that lists the outputs for JLCPCB but unfortunately I have to declare the filter and variant in my main kibot file as the `imports` command only imports outputs, not filters are variants.

It would be great to add support for filters and variants to the import command. This would enable centralizing all JLCPCB items into a single .kibot.yaml file.

**Comment by set-soft** [comment]
Hi @neilenns !
I extended the import syntax to also support the inclusion of filters and variants. You can control what is imported.
The explanation is [here](https://github.com/INTI-CMNB/KiBot#importing-filters-and-variants-from-another-file)

BTW: your `JLCPCB.kibot.yaml` are different from the [example](https://github.com/INTI-CMNB/KiBot/blob/master/docs/samples/JLCPCB_position.kibot.yaml)?

**Comment by neilenns** [comment]
Oh wow that change is awesome! I'll give it a try shortly.

I'm using roughly the same yaml as the example you link to but it's part of a larger flow that outputs for multiple different fab houses. You can see it here: https://github.dev/neilenns/TBM930_De-ice_panel/blob/main/.kibot/release.kibot.yaml. I want to get rid of the JLCPCB items from that file and move it into the JLCPCB import, which now I should be able to do!

**Comment by neilenns** [comment]
@set-soft Can you push an updated Docker image with this change to `setsoft/kicad_auto`? That's how I run all the KiBot stuff. Thanks!

**Comment by set-soft** [comment]
@neilenns : I don't think this is a good idea. The code is new and needs adjusts.
You can clone the repo and call the kibot script from the cloned repo. You don't even need to install it, just invoke the script you got from the git clone.

**Comment by neilenns** [comment]
@set-soft Can you push it under a `dev` tagged image instead? Makes it much easier to work with on windows, I don't have anything cloned locally. It's all done through Docker.

**Comment by set-soft** [comment]
Hi @neilenns !
Try using the `test_import` tag (`INTI-CMNB/KiBot@test_import`)

**Comment by neilenns** [comment]
@set-soft Thanks! Unfortunately that doesn't appear to be a valid Docker image tag. I dug around and noticed you published a `dev` tag 24 minutes ago so I tried this:

`FROM setsoft/kicad_auto:dev`

That does create a container but then fails when running KiBot:

```
ModuleNotFoundError: No module named 'distutils.sysconfig'
```

**Comment by set-soft** [comment]
Hi @neilenns !

> Unfortunately that doesn't appear to be a valid Docker image tag. 

I'm not sure about what the tag must be to be a valid "action tag", do you know it?

> I dug around and noticed you published a dev tag 24 minutes ago so I tried this:

This is a full docker image, not created on the fly. To use it you must use the same mechanism I use for the testing workflows, not a GitHub action. Take a look at the examples mentioned [here](https://github.com/INTI-CMNB/KiBot#usage-for-cicd).

> FROM setsoft/kicad_auto:dev

Where did you add it? Looks like a Dockerfile sentence. You don't need to create another image from `setsoft/kicad_auto:dev` this is a ready to use image.

**Comment by neilenns** [comment]
Ah, I see the issue. We're talking about two different workflows.

I'm trying to test this locally using vscode remote containers, which needs a Docker image as a base. I was using the :latest tag for that, then switched to dev hoping that would have these changes in it.

You're talking about the action to reference from GitHub actions, which I will also use but I wanted to try this locally before modifying my action.

I'll play more with this later today and report back.

**Comment by set-soft** [comment]
Hi @neilenns !

Ok, where did you get the "ModuleNotFoundError: No module named 'distutils.sysconfig'" error?

The `:dev` image is quite similar to the `:latest` image, I just replaced the Debian package by a pip installed repo. You can see the [Dockerfile](https://github.com/INTI-CMNB/KiBot/blob/master/tools/dev_image/Dockerfile).

I did a trivial test running a shell inside the `:dev` image and was able to run the `kibot --version` command. But is true, distutils aren't installed. You can install them adding the following to your Dockerfile:

```
RUN     apt-get update  && \
	apt-get -y install python3-distutils
```

**Comment by set-soft** [comment]
I added `python3-distutils` to the image, this error should go away.

It turns that `python3-distutils` is a dependency of the Debian package, but is normal cases this is part of Python.

**Comment by neilenns** [comment]
Thanks for all your work on this. I gave it another go, just simply creating a new container based on `setsoft/kicad_auto:dev`. When I run `kibot` from the sh prompt it complains `/bin/sh: 1: kibot: not found`. Doing the same thing in the `latest` tagged image results in KiBot running.

Is there a direct path to kibot to use to run it in the dev image instead since it's getting installed slightly differently?

**Comment by neilenns** [comment]
That did the trick! Worked like a charm. Here's a screenshot of KiBot with the new import mechanism working, running in my browser using GitHub Codespaces 😎

![image](https://user-images.githubusercontent.com/9524118/136293788-3174c43d-0843-4bbd-a2a5-4c31e9098f22.png)
