### ISSUE TITLE
Script 'scripts/kibot' not found in metadata

### ISSUE THREAD

**Issue by hoijui** [INTI-CMNB/KiBot#92]
```
$ kibot -h
Traceback (most recent call last):
  File "/usr/local/bin/kibot", line 4, in <module>
    __import__('pkg_resources').run_script('kibot==0.11.0', 'kibot')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1436, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/kibot' not found in metadata at '/usr/lib/python3/dist-packages/kibot-0.11.0.egg-info'
```
I created a deb package from latest master of Kibot (https://github.com/INTI-CMNB/KiBot/commit/d3cd01a24607627365d382e3a7f334b4f36afe46), and installed that on my debian testing system.
I imagine I did something wrong in my setup ... I am not a python universe understander.

**Comment by set-soft** [comment]
You are running a copy installed with `pip`/`setup.py` at `/usr/local/` that is trying to load a package installed at system level in `/usr/`. Look at the message:

```
File "/usr/local/bin/kibot", line 4, in <module>
```

This is local installation. But then:

```
pkg_resources.ResolutionError: Script 'scripts/kibot' not found in metadata at '/usr/lib/python3/dist-packages/kibot-0.11.0.egg-info'
```

This is system tool installation (from the .deb).

You should remove the package installed with `pip`/`setup.py` to avoid conflicts.

Also note that you don't really need to install KiBot if you need to run a git copy, just run the script from the repo. Just use the full path to `REPO/src/kibot` 

I agree we need a new Debian package, but the current git code adds various things that aren't covered by the regression tests.
